; See wNextBonusStage
DEF BONUS_STAGE_ORDER_GENGAR  EQU 0
DEF BONUS_STAGE_ORDER_MEWTWO  EQU 1
DEF BONUS_STAGE_ORDER_MEOWTH  EQU 2
DEF BONUS_STAGE_ORDER_DIGLETT EQU 3
DEF BONUS_STAGE_ORDER_SEEL    EQU 4
