const_value = 0
	
	const CATCHEM_BULBASAUR     ; $0
	const CATCHEM_CHARMANDER    ; $1
	const CATCHEM_SQUIRTLE      ; $2
	const CATCHEM_CATERPIE      ; $3
	const CATCHEM_WEEDLE        ; $4
	const CATCHEM_PIDGEY        ; $5
	const CATCHEM_RATTATA       ; $6
	const CATCHEM_SPEAROW       ; $7
	const CATCHEM_EKANS         ; $8
	const CATCHEM_PIKACHU       ; $9
	const CATCHEM_SANDSHREW     ; $a
	const CATCHEM_NIDORAN_F     ; $b
	const CATCHEM_NIDORAN_M     ; $c
	const CATCHEM_CLEFAIRY      ; $d
	const CATCHEM_VULPIX        ; $e
	const CATCHEM_JIGGLYPUFF    ; $f
	const CATCHEM_ZUBAT         ; $10
	const CATCHEM_ODDISH        ; $11
	const CATCHEM_PARAS         ; $12
	const CATCHEM_VENONAT       ; $13
	const CATCHEM_DIGLETT       ; $14
	const CATCHEM_MEOWTH        ; $15
	const CATCHEM_PSYDUCK       ; $16
	const CATCHEM_MANKEY        ; $17
	const CATCHEM_GROWLITHE     ; $18
	const CATCHEM_POLIWAG       ; $19
	const CATCHEM_ABRA          ; $1a
	const CATCHEM_MACHOP        ; $1b
	const CATCHEM_BELLSPROUT    ; $1c
	const CATCHEM_TENTACOOL     ; $1d
	const CATCHEM_GEODUDE       ; $1e
	const CATCHEM_PONYTA        ; $1f
	const CATCHEM_SLOWPOKE      ; $20
	const CATCHEM_MAGNEMITE     ; $21
	const CATCHEM_FARFETCH_D    ; $22
	const CATCHEM_DODUO         ; $23
	const CATCHEM_SEEL          ; $24
	const CATCHEM_GRIMER        ; $25
	const CATCHEM_SHELLDER      ; $26
	const CATCHEM_GASTLY        ; $27
	const CATCHEM_ONIX          ; $28
	const CATCHEM_DROWZEE       ; $29
	const CATCHEM_KRABBY        ; $2a
	const CATCHEM_VOLTORB       ; $2b
	const CATCHEM_EXEGGCUTE     ; $2c
	const CATCHEM_CUBONE        ; $2d
	const CATCHEM_HITMONLEE     ; $2e
	const CATCHEM_HITMONCHAN    ; $2f
	const CATCHEM_LICKITUNG     ; $30
	const CATCHEM_KOFFING       ; $31
	const CATCHEM_RHYHORN       ; $32
	const CATCHEM_CHANSEY       ; $33
	const CATCHEM_TANGELA       ; $34
	const CATCHEM_KANGASKHAN    ; $35
	const CATCHEM_HORSEA        ; $36
	const CATCHEM_GOLDEEN       ; $37
	const CATCHEM_STARYU        ; $38
	const CATCHEM_MR_MIME       ; $39
	const CATCHEM_SCYTHER       ; $3a
	const CATCHEM_JYNX          ; $3b
	const CATCHEM_ELECTABUZZ    ; $3c
	const CATCHEM_MAGMAR        ; $3d
	const CATCHEM_PINSIR        ; $3e
	const CATCHEM_TAUROS        ; $3f
	const CATCHEM_MAGIKARP      ; $40
	const CATCHEM_LAPRAS        ; $41
	const CATCHEM_DITTO         ; $42
	const CATCHEM_EEVEE         ; $43
	const CATCHEM_PORYGON       ; $44
	const CATCHEM_OMANYTE       ; $45
	const CATCHEM_KABUTO        ; $46
	const CATCHEM_AERODACTYL    ; $47
	const CATCHEM_SNORLAX       ; $48
	const CATCHEM_ARTICUNO      ; $49
	const CATCHEM_ZAPDOS        ; $4a
	const CATCHEM_MOLTRES       ; $4b
	const CATCHEM_DRATINI       ; $4c
	const CATCHEM_MEWTWO        ; $4d
	const CATCHEM_MEW           ; $4e
