DEF EVO_THUNDER_STONE  EQU $01
DEF EVO_MOON_STONE     EQU $02
DEF EVO_FIRE_STONE     EQU $03
DEF EVO_LEAF_STONE     EQU $04
DEF EVO_WATER_STONE    EQU $05
DEF EVO_LINK_CABLE     EQU $06
DEF EVO_EXPERIENCE     EQU $07
