const_value = 0
	
	const EVOLINE_BULBASAUR     ; $0
	const EVOLINE_CHARMANDER    ; $1
	const EVOLINE_SQUIRTLE      ; $2
	const EVOLINE_CATERPIE      ; $3
	const EVOLINE_WEEDLE        ; $4
	const EVOLINE_PIDGEY        ; $5
	const EVOLINE_RATTATA       ; $6
	const EVOLINE_SPEAROW       ; $7
	const EVOLINE_EKANS         ; $8
	const EVOLINE_PIKACHU       ; $9
	const EVOLINE_SANDSHREW     ; $a
	const EVOLINE_NIDORAN_F     ; $b
	const EVOLINE_NIDORAN_M     ; $c
	const EVOLINE_CLEFAIRY      ; $d
	const EVOLINE_VULPIX        ; $e
	const EVOLINE_JIGGLYPUFF    ; $f
	const EVOLINE_ZUBAT         ; $10
	const EVOLINE_ODDISH        ; $11
	const EVOLINE_PARAS         ; $12
	const EVOLINE_VENONAT       ; $13
	const EVOLINE_DIGLETT       ; $14
	const EVOLINE_MEOWTH        ; $15
	const EVOLINE_PSYDUCK       ; $16
	const EVOLINE_MANKEY        ; $17
	const EVOLINE_GROWLITHE     ; $18
	const EVOLINE_POLIWAG       ; $19
	const EVOLINE_ABRA          ; $1a
	const EVOLINE_MACHOP        ; $1b
	const EVOLINE_BELLSPROUT    ; $1c
	const EVOLINE_TENTACOOL     ; $1d
	const EVOLINE_GEODUDE       ; $1e
	const EVOLINE_PONYTA        ; $1f
	const EVOLINE_SLOWPOKE      ; $20
	const EVOLINE_MAGNEMITE     ; $21
	const EVOLINE_FARFETCH_D    ; $22
	const EVOLINE_DODUO         ; $23
	const EVOLINE_SEEL          ; $24
	const EVOLINE_GRIMER        ; $25
	const EVOLINE_SHELLDER      ; $26
	const EVOLINE_GASTLY        ; $27
	const EVOLINE_ONIX          ; $28
	const EVOLINE_DROWZEE       ; $29
	const EVOLINE_KRABBY        ; $2a
	const EVOLINE_VOLTORB       ; $2b
	const EVOLINE_EXEGGCUTE     ; $2c
	const EVOLINE_CUBONE        ; $2d
	const EVOLINE_HITMONLEE     ; $2e
	const EVOLINE_HITMONCHAN    ; $2f
	const EVOLINE_LICKITUNG     ; $30
	const EVOLINE_KOFFING       ; $31
	const EVOLINE_RHYHORN       ; $32
	const EVOLINE_CHANSEY       ; $33
	const EVOLINE_TANGELA       ; $34
	const EVOLINE_KANGASKHAN    ; $35
	const EVOLINE_HORSEA        ; $36
	const EVOLINE_GOLDEEN       ; $37
	const EVOLINE_STARYU        ; $38
	const EVOLINE_MR_MIME       ; $39
	const EVOLINE_SCYTHER       ; $3a
	const EVOLINE_JYNX          ; $3b
	const EVOLINE_ELECTABUZZ    ; $3c
	const EVOLINE_MAGMAR        ; $3d
	const EVOLINE_PINSIR        ; $3e
	const EVOLINE_TAUROS        ; $3f
	const EVOLINE_MAGIKARP      ; $40
	const EVOLINE_LAPRAS        ; $41
	const EVOLINE_DITTO         ; $42
	const EVOLINE_EEVEE         ; $43
	const EVOLINE_PORYGON       ; $44
	const EVOLINE_OMANYTE       ; $45
	const EVOLINE_KABUTO        ; $46
	const EVOLINE_AERODACTYL    ; $47
	const EVOLINE_SNORLAX       ; $48
	const EVOLINE_ARTICUNO      ; $49
	const EVOLINE_ZAPDOS        ; $4a
	const EVOLINE_MOLTRES       ; $4b
	const EVOLINE_DRATINI       ; $4c
	const EVOLINE_MEWTWO        ; $4d
	const EVOLINE_MEW           ; $4e
