MAX_PIKACHU_SAVER_CHARGE EQU 15

CATCHEM_MODE_SLOT_REWARD   EQU 1
EVOLUTION_MODE_SLOT_REWARD EQU 2

SPECIAL_MODE_CATCHEM   EQU 1
SPECIAL_MODE_EVOLUTION EQU 2
SPECIAL_MODE_MAP_MOVE  EQU 2 ; shares value with SPECIAL_MODE_EVOLUTION

; To encounter Mew, you must first beat Mewtwo's bonus stage 2 times.
NUM_MEWTWO_COMPLETIONS_FOR_MEW EQU 2

MAX_BONUS_MULTIPLIER              EQU 99
MAX_BONUS_MULTIPLIER_FIELD_EVENTS EQU 11

MAP_MOVE_FRAMES_COUNTER        EQU  480 ; 8 seconds until the map move counter decrease by 1
PINBALL_UPGRADE_FRAMES_COUNTER EQU 3600 ; ~1 minute until the pinball type degrades one stage. (e.g. Great Ball -> Pokeball)

SPECIAL_COLLISION_NOTHING EQU 0
SPECIAL_COLLISION_LEFT_TRIGGER EQU 1
SPECIAL_COLLISION_RIGHT_TRIGGER EQU 2
SPECIAL_COLLISION_STARYU_ALLY_TRIGGER EQU 3
SPECIAL_COLLISION_VOLTORB EQU 4
SPECIAL_COLLISION_SHELLDER EQU 4
SPECIAL_COLLISION_BELLSPROUT EQU 5
SPECIAL_COLLISION_STARYU EQU 6
SPECIAL_COLLISION_LEFT_DIGLETT EQU 7
SPECIAL_COLLISION_POLIWAG EQU 7
SPECIAL_COLLISION_RIGHT_DIGLETT EQU 8
SPECIAL_COLLISION_PPSYDUCK EQU 8
SPECIAL_COLLISION_BALL_UPGRADE EQU 11
SPECIAL_COLLISION_SPINNER EQU 12
SPECIAL_COLLISION_SLOT_HOLE EQU 13
SPECIAL_COLLISION_CLOYSTER EQU 14
SPECIAL_COLLISION_SLOWPOKE EQU 15
