MAX_PIKACHU_SAVER_CHARGE EQU 15

CATCHEM_MODE_SLOT_REWARD   EQU 1
EVOLUTION_MODE_SLOT_REWARD EQU 2

SPECIAL_MODE_CATCHEM   EQU 1
SPECIAL_MODE_EVOLUTION EQU 2
SPECIAL_MODE_MAP_MOVE  EQU 2 ; shares value with SPECIAL_MODE_EVOLUTION

; To encounter Mew, you must first beat Mewtwo's bonus stage 2 times.
NUM_MEWTWO_COMPLETIONS_FOR_MEW EQU 2

MAX_BONUS_MULTIPLIER              EQU 99
MAX_BONUS_MULTIPLIER_FIELD_EVENTS EQU 11
