const_value = 1

	const BULBASAUR   ; $1
	const IVYSAUR     ; $2
	const VENUSAUR    ; $3
	const CHARMANDER  ; $4
	const CHARMELEON  ; $5
	const CHARIZARD   ; $6
	const SQUIRTLE    ; $7
	const WARTORTLE   ; $8
	const BLASTOISE   ; $9
	const CATERPIE    ; $a
	const METAPOD     ; $b
	const BUTTERFREE  ; $c
	const WEEDLE      ; $d
	const KAKUNA      ; $e
	const BEEDRILL    ; $f
	const PIDGEY      ; $10
	const PIDGEOTTO   ; $11
	const PIDGEOT     ; $12
	const RATTATA     ; $13
	const RATICATE    ; $14
	const SPEAROW     ; $15
	const FEAROW      ; $16
	const EKANS       ; $17
	const ARBOK       ; $18
	const PIKACHU     ; $19
	const RAICHU      ; $1a
	const SANDSHREW   ; $1b
	const SANDSLASH   ; $1c
	const NIDORAN_F   ; $1d
	const NIDORINA    ; $1e
	const NIDOQUEEN   ; $1f
	const NIDORAN_M   ; $20
	const NIDORINO    ; $21
	const NIDOKING    ; $22
	const CLEFAIRY    ; $23
	const CLEFABLE    ; $24
	const VULPIX      ; $25
	const NINETALES   ; $26
	const JIGGLYPUFF  ; $27
	const WIGGLYTUFF  ; $28
	const ZUBAT       ; $29
	const GOLBAT      ; $2a
	const ODDISH      ; $2b
	const GLOOM       ; $2c
	const VILEPLUME   ; $2d
	const PARAS       ; $2e
	const PARASECT    ; $2f
	const VENONAT     ; $30
	const VENOMOTH    ; $31
	const DIGLETT     ; $32
	const DUGTRIO     ; $33
	const MEOWTH      ; $34
	const PERSIAN     ; $35
	const PSYDUCK     ; $36
	const GOLDUCK     ; $37
	const MANKEY      ; $38
	const PRIMEAPE    ; $39
	const GROWLITHE   ; $3a
	const ARCANINE    ; $3b
	const POLIWAG     ; $3c
	const POLIWHIRL   ; $3d
	const POLIWRATH   ; $3e
	const ABRA        ; $3f
	const KADABRA     ; $40
	const ALAKAZAM    ; $41
	const MACHOP      ; $42
	const MACHOKE     ; $43
	const MACHAMP     ; $44
	const BELLSPROUT  ; $45
	const WEEPINBELL  ; $46
	const VICTREEBEL  ; $47
	const TENTACOOL   ; $48
	const TENTACRUEL  ; $49
	const GEODUDE     ; $4a
	const GRAVELER    ; $4b
	const GOLEM       ; $4c
	const PONYTA      ; $4d
	const RAPIDASH    ; $4e
	const SLOWPOKE    ; $4f
	const SLOWBRO     ; $50
	const MAGNEMITE   ; $51
	const MAGNETON    ; $52
	const FARFETCH_D  ; $53
	const DODUO       ; $54
	const DODRIO      ; $55
	const SEEL        ; $56
	const DEWGONG     ; $57
	const GRIMER      ; $58
	const MUK         ; $59
	const SHELLDER    ; $5a
	const CLOYSTER    ; $5b
	const GASTLY      ; $5c
	const HAUNTER     ; $5d
	const GENGAR      ; $5e
	const ONIX        ; $5f
	const DROWZEE     ; $60
	const HYPNO       ; $61
	const KRABBY      ; $62
	const KINGLER     ; $63
	const VOLTORB     ; $64
	const ELECTRODE   ; $65
	const EXEGGCUTE   ; $66
	const EXEGGUTOR   ; $67
	const CUBONE      ; $68
	const MAROWAK     ; $69
	const HITMONLEE   ; $6a
	const HITMONCHAN  ; $6b
	const LICKITUNG   ; $6c
	const KOFFING     ; $6d
	const WEEZING     ; $6e
	const RHYHORN     ; $6f
	const RHYDON      ; $70
	const CHANSEY     ; $71
	const TANGELA     ; $72
	const KANGASKHAN  ; $73
	const HORSEA      ; $74
	const SEADRA      ; $75
	const GOLDEEN     ; $76
	const SEAKING     ; $77
	const STARYU      ; $78
	const STARMIE     ; $79
	const MR_MIME     ; $7a
	const SCYTHER     ; $7b
	const JYNX        ; $7c
	const ELECTABUZZ  ; $7d
	const MAGMAR      ; $7e
	const PINSIR      ; $7f
	const TAUROS      ; $80
	const MAGIKARP    ; $81
	const GYARADOS    ; $82
	const LAPRAS      ; $83
	const DITTO       ; $84
	const EEVEE       ; $85
	const VAPOREON    ; $86
	const JOLTEON     ; $87
	const FLAREON     ; $88
	const PORYGON     ; $89
	const OMANYTE     ; $8a
	const OMASTAR     ; $8b
	const KABUTO      ; $8c
	const KABUTOPS    ; $8d
	const AERODACTYL  ; $8e
	const SNORLAX     ; $8f
	const ARTICUNO    ; $90
	const ZAPDOS      ; $91
	const MOLTRES     ; $92
	const DRATINI     ; $93
	const DRAGONAIR   ; $94
	const DRAGONITE   ; $95
	const MEWTWO      ; $96
	const MEW         ; $97

NUM_POKEMON EQU 151
