DEF NUM_SONGS EQU $17

DEF MUSIC_NOTHING EQU $00

; Bank $F Songs
DEF MUSIC_RED_FIELD         EQU $01
DEF MUSIC_CATCH_EM_RED      EQU $02
DEF MUSIC_HURRY_UP_RED      EQU $03
DEF MUSIC_POKEDEX           EQU $04
DEF MUSIC_GASTLY_GRAVEYARD  EQU $05
DEF MUSIC_HAUNTER_GRAVEYARD EQU $06
DEF MUSIC_GENGAR_GRAVEYARD  EQU $07

; Bank $10 Songs
DEF MUSIC_BLUE_FIELD    EQU $01
DEF MUSIC_CATCH_EM_BLUE EQU $02
DEF MUSIC_HURRY_UP_BLUE EQU $03
DEF MUSIC_HI_SCORE      EQU $04
DEF MUSIC_GAME_OVER     EQU $05

; Bank $11 Songs
DEF MUSIC_WHACK_DIGLETT EQU $01
DEF MUSIC_WHACK_DUGTRIO EQU $02
DEF MUSIC_SEEL_STAGE    EQU $03
DEF MUSIC_TITLE_SCREEN  EQU $04

; Bank $12 Songs
DEF MUSIC_MEWTWO_STAGE EQU $01
DEF MUSIC_OPTIONS      EQU $02
DEF MUSIC_FIELD_SELECT EQU $03
DEF MUSIC_MEOWTH_STAGE EQU $04

; Bank $13 Songs
DEF MUSIC_END_CREDITS EQU $01
DEF MUSIC_NAME_ENTRY  EQU $02
