NUM_SONGS EQU $17

MUSIC_NOTHING EQU $00

; Bank $F Songs
MUSIC_RED_FIELD         EQU $01
MUSIC_CATCH_EM_RED      EQU $02
MUSIC_HURRY_UP_RED      EQU $03
MUSIC_POKEDEX           EQU $04
MUSIC_GASTLY_GRAVEYARD  EQU $05
MUSIC_HAUNTER_GRAVEYARD EQU $06
MUSIC_GENGAR_GRAVEYARD  EQU $07

; Bank $10 Songs
MUSIC_BLUE_FIELD    EQU $01
MUSIC_CATCH_EM_BLUE EQU $02
MUSIC_HURRY_UP_BLUE EQU $03
MUSIC_HI_SCORE      EQU $04
MUSIC_GAME_OVER     EQU $05

; Bank $11 Songs
MUSIC_WHACK_DIGLETT EQU $01
MUSIC_WHACK_DUGTRIO EQU $02
MUSIC_SEEL_STAGE    EQU $03
MUSIC_TITLE_SCREEN  EQU $04

; Bank $12 Songs
MUSIC_MEWTWO_STAGE EQU $01
MUSIC_OPTIONS      EQU $02
MUSIC_FIELD_SELECT EQU $03
MUSIC_MEOWTH_STAGE EQU $04

; Bank $13 Songs
MUSIC_END_CREDITS EQU $01
MUSIC_NAME_ENTRY  EQU $02
