const_value = 0

	const SPECIES_SEED       ; $0
	const SPECIES_LIZARD     ; $1
	const SPECIES_FLAME      ; $2
	const SPECIES_TINYTURTLE ; $3
	const SPECIES_TURTLE     ; $4
	const SPECIES_SHELLFISH  ; $5
	const SPECIES_WORM       ; $6
	const SPECIES_COCOON     ; $7
	const SPECIES_BUTTERFLY  ; $8
	const SPECIES_HAIRY_BUG  ; $9
	const SPECIES_POISON_BEE ; $A
	const SPECIES_TINY_BIRD  ; $B
	const SPECIES_BIRD       ; $C
	const SPECIES_MOUSE      ; $D
	const SPECIES_BEAK       ; $E
	const SPECIES_SNAKE      ; $F
	const SPECIES_COBRA      ; $10
	const SPECIES_POISON_PIN ; $11
	const SPECIES_DRILL      ; $12
	const SPECIES_FAIRY      ; $13
	const SPECIES_FOX        ; $14
	const SPECIES_BALLOON    ; $15
	const SPECIES_BAT        ; $16
	const SPECIES_WEED       ; $17
	const SPECIES_FLOWER     ; $18
	const SPECIES_MUSHROOM   ; $19
	const SPECIES_INSECT     ; $1A
	const SPECIES_POISONMOTH ; $1B
	const SPECIES_MOLE       ; $1C
	const SPECIES_SCRATCHCAT ; $1D
	const SPECIES_CLASSY_CAT ; $1E
	const SPECIES_DUCK       ; $1F
	const SPECIES_PIG_MONKEY ; $20
	const SPECIES_PUPPY      ; $21
	const SPECIES_LEGENDARY  ; $22
	const SPECIES_TADPOLE    ; $23
	const SPECIES_PSI        ; $24
	const SPECIES_SUPERPOWER ; $25
	const SPECIES_FLYCATCHER ; $26
	const SPECIES_JELLYFISH  ; $27
	const SPECIES_ROCK       ; $28
	const SPECIES_MEGATON    ; $29
	const SPECIES_FIRE_HORSE ; $2A
	const SPECIES_DOPEY      ; $2B
	const SPECIES_HERMITCRAB ; $2C
	const SPECIES_MAGNET     ; $2D
	const SPECIES_WILD_DUCK  ; $2E
	const SPECIES_TWIN_BIRD  ; $2F
	const SPECIES_TRIPLEBIRD ; $30
	const SPECIES_SEA_LION   ; $31
	const SPECIES_SLUDGE     ; $32
	const SPECIES_BIVALVE    ; $33
	const SPECIES_GAS        ; $34
	const SPECIES_SHADOW     ; $35
	const SPECIES_ROCK_SNAKE ; $36
	const SPECIES_HYPNOSIS   ; $37
	const SPECIES_RIVER_CRAB ; $38
	const SPECIES_PINCER     ; $39
	const SPECIES_BALL       ; $3A
	const SPECIES_EGG        ; $3B
	const SPECIES_COCONUT    ; $3C
	const SPECIES_LONELY     ; $3D
	const SPECIES_BONEKEEPER ; $3E
	const SPECIES_KICKING    ; $3F
	const SPECIES_PUNCHING   ; $40
	const SPECIES_LICKING    ; $41
	const SPECIES_POISON_GAS ; $42
	const SPECIES_SPIKES     ; $43
	const SPECIES_VINE       ; $44
	const SPECIES_PARENT     ; $45
	const SPECIES_DRAGON     ; $46
	const SPECIES_GOLDFISH   ; $47
	const SPECIES_STARSHAPE  ; $48
	const SPECIES_MYSTERIOUS ; $49
	const SPECIES_BARRIER    ; $4A
	const SPECIES_MANTIS     ; $4B
	const SPECIES_HUMANSHAPE ; $4C
	const SPECIES_ELECTRIC   ; $4D
	const SPECIES_SPITFIRE   ; $4E
	const SPECIES_STAGBEETLE ; $4F
	const SPECIES_WILD_BULL  ; $50
	const SPECIES_FISH       ; $51
	const SPECIES_ATROCIOUS  ; $52
	const SPECIES_TRANSPORT  ; $53
	const SPECIES_TRANSFORM  ; $54
	const SPECIES_EVOLUTION  ; $55
	const SPECIES_BUBBLE_JET ; $56
	const SPECIES_LIGHTNING  ; $57
	const SPECIES_FLAME_2    ; $58
	const SPECIES_VIRTUAL    ; $59
	const SPECIES_SPIRAL     ; $5A
	const SPECIES_FOSSIL     ; $5B
	const SPECIES_SLEEPING   ; $5C
	const SPECIES_FREEZE     ; $5D
	const SPECIES_GENETIC    ; $5E
	const SPECIES_NEW_SPECIE ; $5F
	const SPECIES_RAT        ; $60
