DEF STAGE_RED_FIELD_TOP      EQU $0
DEF STAGE_RED_FIELD_BOTTOM   EQU $1
; XXX EQU $2
; XXX EQU $3
DEF STAGE_BLUE_FIELD_TOP     EQU $4
DEF STAGE_BLUE_FIELD_BOTTOM  EQU $5

DEF FIRST_BONUS_STAGE        EQU $6
; STAGE_GENGAR_BONUS     EQU $6  ; buggy
DEF STAGE_GENGAR_BONUS       EQU $7
; STAGE_MEWTWO_BONUS     EQU $8  ; buggy
DEF STAGE_MEWTWO_BONUS       EQU $9
; STAGE_MEOWTH_BONUS     EQU $a  ; buggy
DEF STAGE_MEOWTH_BONUS       EQU $b
; STAGE_DIGLETT_BONUS    EQU $c  ; buggy
DEF STAGE_DIGLETT_BONUS      EQU $d
; STAGE_SEEL_BONUS       EQU $e  ; buggy
DEF STAGE_SEEL_BONUS         EQU $f
