INCLUDE "hram.asm"
INCLUDE "vram.asm"
INCLUDE "gbhw.asm"

INCLUDE "constants/ball_types.asm"
INCLUDE "constants/diglett_stage_constants.asm"
INCLUDE "constants/evolution_line_constants.asm"
INCLUDE "constants/evolution_type_constants.asm"
INCLUDE "constants/joy_constants.asm"
INCLUDE "constants/map_constants.asm"
INCLUDE "constants/pinball_game_constants.asm"
INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/screen_constants.asm"
INCLUDE "constants/song_constants.asm"
INCLUDE "constants/sound_effect_constants.asm"
INCLUDE "constants/species_constants.asm"
INCLUDE "constants/stage_constants.asm"
