INCLUDE "hram.asm"
INCLUDE "vram.asm"

INCLUDE "constants/evolution_line_constants.asm"
INCLUDE "constants/joy_constants.asm"
INCLUDE "constants/map_constants.asm"
INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/screen_constants.asm"
INCLUDE "constants/song_constants.asm"
INCLUDE "constants/sound_effect_constants.asm"
INCLUDE "constants/stage_constants.asm"
