INCLUDE "constants.asm"

SECTION "Home", ROM0

INCBIN "baserom.gbc",$0,$100

SECTION "Entry", ROM0 [$100]

	nop
	jp Start

SECTION "Header", ROM0 [$104]

	; The header is generated by rgbfix.
	; The space here is allocated to prevent code from being overwritten.
	ds $150 - $104

SECTION "Main", ROM0

Start: ; 0x150
    ld [$fffe], a
    ld sp, $fffe
    di
    xor a
    ld [$ff0f], a
    ld a, [$ff40]
    bit 7, a
    jr nz, .asm_163
    set 7, a
    ld [$ff40], a
.asm_163
    ld bc, $0002
    call Func_948
.asm_169
    ld a, [$ff44]
    cp $91
    jr c, .asm_169
    ld a, $81
    ld [$ff40], a
    xor a
    ld [$ff47], a
    ld [$ff48], a
    ld [$ff49], a
    ld bc, $0002
    call Func_948
.asm_180
    ld a, [$ff44]
    cp $91
    jr c, .asm_180
    xor a
    ld [$ff40], a
    ld hl, wc000
    ld bc, $2000
    call Func_654
    ld hl, $8000
    ld bc, $1000
    call Func_654
    ld a, $a
    ld [$0000], a
    ld a, $1
    ld [$2000], a
    ld a, $0
    ld [$6000], a
    ld a, $0
    ld [$4000], a
    ld a, $1
    ld [$fff8], a
    ld a, $1
    ld [$6000], a
    ld a, $0
    ld [$4000], a
    ld sp, $dfff
    ld hl, $ff80
    ld bc, $007e
    call Func_654
    call Func_5f7
    call Func_916
    xor a
    ld [$d7fb], a
    ld [$d7fc], a
    ld [$d7fd], a
    ld [$ffb0], a
    ld [$ffb1], a
    ld [$d8e1], a
    ld [$d7fe], a
    ld [$fffc], a
    ld hl, $ff9e
    xor a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld [hli], a
    ld a, $8f
    ld [hli], a
    ld a, $a6
    ld [hli], a
    ld a, $0
    ld [$d849], a
    ld [$d84a], a
    ld a, $f
    call Func_52c
    call Func_23b
    ld a, [$fffe]
    and a
    jr nz, .asm_222
    call Func_12f8
    rl a
    and $1
    ld [$fffb], a
    call Func_13a8
    ld a, [$fffb]
    and a
    jr z, .asm_222
    ld a, $1
    ld [$d917], a
.asm_222
    ld a, $1
    ld [$ffff], a
    ei
    ld a, $ff
    ld [$d810], a
    call Func_97a
    xor a
    ld [$daa3], a
    ld a, $0
    ld hl, $1ffc
    call Func_549
Func_23b: ; 0x23b
    ld a, [$fffe]
    cp $11
    jr nz, .asm_248
    ld a, $1
    ld [$fffe], a
    ld [$fffd], a
    ret
.asm_248
    xor a
    ld [$fffe], a
    ld [$fffd], a
    ret

INCBIN "baserom.gbc",$24e,$468 - $24e

Func_468: ; 0x468
    ld a, [$ff40]
    bit 7, a
    ret z
    ld hl, $ffb2
    xor a
    ld [hl], a
.asm_472
    ld a, [hl]
    and a
    jr z, .asm_472
    ret

INCBIN "baserom.gbc",$477,$52c - $477

Func_52c: ; 0x52c
    di
    ld [$d85b], a
    ei
    ret

Func_532: ; 0x532
    ld e, a
    ld d, $0
    sla e
    rl d
    sla e
    rl d
    pop hl
    add hl, de
    ld e, [hl]
    inc hl
    ld d, [hl]
    inc hl
    ld a, [hl]
    ld h, d
    ld l, e
    jp Func_54f

Func_549: ; 0x549
    ld [$fff8], a
    ld [$2000], a
    jp [hl]

Func_54f: ; 0x54f
    ld e, a
    ld a, [$fff8]
    cp e
    jr z, .asm_570
    push af
    ld a, e
    call .asm_55f
    call .asm_570
    pop de
    ld a, d
.asm_55f
    push hl
    push de
    ld hl, $ffff
    ld d, [hl]
    ld [hl], $0
    ld [$2000], a
    ld [$fff8], a
    ld [hl], d
    pop de
    pop hl
    ret
.asm_570
    ld a, [$ff8b]
    ld e, a
    ld a, [$ff8a]
    jp [hl]

INCBIN "baserom.gbc",$576,$588 - $576

Func_588: ; 0x588
    ld a, [$ffc4]
    and a
    call nz, Func_597
    ld a, [$ff9e]
    set 7, a
    ld [$ff40], a
    ld [$ff9e], a
    ret

Func_597: ; 0x597
    ld de, $ff68
    ld a, $80
    ld [de], a
    inc de
    ld b, $8
.asm_5a0
    ld a, [$d80c]
    call Func_5c2
    dec b
    jr nz, .asm_5a0
    ld de, $ff6a
    ld a, $80
    ld [de], a
    inc de
    ld b, $4
.asm_5b2
    ld a, [$d80d]
    call Func_5c2
    ld a, [$d80e]
    call Func_5c2
    dec b
    jr nz, .asm_5b2
    ret

Func_5c2: ; 0x5c2
    push bc
    ld b, $4
.asm_5c5
    push af
    push bc
    and $3
    sla a
    ld c, a
    ld b, $0
    ld hl, $05e1
    add hl, bc
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    pop bc
    pop af
    srl a
    srl a
    dec b
    jr nz, .asm_5c5
    pop bc
    ret

INCBIN "baserom.gbc",$5e1,$5f7 - $5e1

Func_5f7: ; 0x5f7
    ld c, $80
    ld b, $a
    ld hl, $0605 ; todo
.asm_5fe
    ld a, [hli]
    ld [$ff00+c], a
    inc c
    dec b
    jr nz, .asm_5fe
    ret

INCBIN "baserom.gbc",$605,$654 - $605

Func_654: ; 0x654
    xor a
    dec bc
.asm_656
    ld [hli], a
    dec bc
    bit 7, b
    jr z, .asm_656
    ret

Func_65d: ; 0x65d
    ld a, [hli]
    ld [de], a
    inc de
    dec bc
    ld a, c
    or b
    jr nz, Func_65d
    ret

INCBIN "baserom.gbc",$666,$6a4 - $666

Func_6a4: ; 0x6a4
    sla a
    ld c, a
    ld b, $0
    add hl, bc
    ld a, [hli]
    ld h, [hl]
    ld l, a
.asm_6ad
    ld a, [hli]
    ld c, a
    and [hl]
    cp $ff
    ret z
    ld a, [hli]
    ld b, a
    push hl
    push bc
    ld a, [hli]
    ld e, [hl]
    inc hl
    ld d, [hl]
    inc hl
    ld c, [hl]
    inc hl
    ld b, [hl]
    inc hl
    pop hl
    call Func_6cb
    pop hl
    ld bc, $0005
    add hl, bc
    jr .asm_6ad

Func_6cb: ; 0x6cb
    srl b
    rr c
    jp c, Func_6fd
    jp Func_6d5 ; This jumps to the next instruction... Strange.

Func_6d5: ; 0x6d5
    ld [$fffa], a
    ld a, [$fff8]
    push af
    ld a, [$fffa]
    ld [$fff8], a
    ld [$2000], a
    srl b
    rr c
    rl a
    and $1
    ld [$ff4f], a
.asm_6eb
    ld a, [hli]
    ld [de], a
    inc de
    dec bc
    ld a, c
    or b
    jr nz, .asm_6eb
    xor a
    ld [$ff4f], a
    pop af
    ld [$fff8], a
    ld [$2000], a
    ret

Func_6fd: ; 0x6fd
    ld [$fffa], a
    ld a, [$fff8]
    push af
    ld a, [$fffa]
    ld [$fff8], a
    ld [$2000], a
    ld a, e
    bit 6, a
    jr nz, .asm_717
    ld de, $ff68
    call Func_724
    jr z, .asm_71d
    xor a
.asm_717
    ld de, $ff6a
    call Func_724
.asm_71d
    pop af
    ld [$fff8], a
    ld [$2000], a
    ret

Func_724: ; 0x724
    res 6, a
    ld b, a
    set 7, a
    ld [de], a
    inc de
.asm_72b
    ld a, [hli]
    ld [de], a
    inc b
    dec c
    ret z
    bit 6, b
    jr z, .asm_72b
    ret

INCBIN "baserom.gbc",$735,$916 - $735

Func_916: ; 0x916
    ld hl, wOAMBuffer
    ld b, $a0
    ld a, $f0
.asm_91d
    ld [hli], a
    dec b
    jr nz, .asm_91d
    xor a
    ld [$d802], a
    ret

Func_926: ; 0x926
    ld a, [$d802]
    cp $a0
    jr nc, .asm_93a
    ld l, a
    ld h, $d0
    cpl
    add $a1
    ld b, a
    ld a, $f0
.asm_936
    ld [hli], a
    dec b
    jr nz, .asm_936
.asm_93a
    xor a
    ld [$d802], a
    ret

Func_93f: ; 0x93f
    push bc
    rst $10
    pop bc
    dec bc
    ld a, c
    or b
    jr nz, Func_93f
    ret

Func_948: ; 0x948
    ld de, $06d6
.asm_94b
    nop
    nop
    nop
    dec de
    ld a, d
    or e
    jr nz, .asm_94b
    dec bc
    ld a, b
    or c
    jr nz, Func_948
    ret

Func_959: ; 0x959
    push bc
    push de
    push hl
    ld a, [$d811]
    ld c, a
    ld b, $0
    inc a
    cp $37
    jr nz, .asm_96e
    call Func_9fa
    xor a
    ld bc, $0000
.asm_96e
    ld [$d811], a
    ld hl, $d812
    add hl, bc
    ld a, [hl]
    pop hl
    pop de
    pop bc
    ret

Func_97a: ; 0x97a
    ld a, [$d810]
    ld d, a
    ld a, $0
    ld a, [$afff]
.asm_983
    cp d
    jr c, .asm_989
    sub d
    jr .asm_983
.asm_989
    ld [$d80f], a
    ld [$d848], a
    ld e, $1
    ld hl, $09c4 ; todo
    ld a, $36
.asm_996
    push af
    ld c, [hl]
    inc hl
    ld b, $0
    push hl
    ld hl, $d812
    add hl, bc
    ld [hl], e
    ld a, [$d80f]
    sub e
    jr nc, .asm_9a8
    add d
.asm_9a8
    ld e, a
    ld a, [hl]
    ld [$d80f], a
    pop hl
    pop af
    dec a
    jr nz, .asm_996
    call Func_9fa
    call Func_9fa
    call Func_9fa
    ld a, $0
    call Func_959
    ld [$afff], a
    ret

INCBIN "baserom.gbc",$9c4,$9fa - $9c4

Func_9fa: ; 0x9fa
    ld a, [$d810]
    ld d, a
    ld bc, $d812
    ld hl, $d831
    ld e, $18
.asm_a06
    ld a, [bc]
    sub [hl]
    jr nc, .asm_a0b
    add d
.asm_a0b
    ld [bc], a
    dec e
    jr nz, .asm_a06
    ld bc, $d82a
    ld hl, $d812
    ld e, $1f
.asm_a17
    ld a, [bc]
    sub [hl]
    jr nc, .asm_a1c
    add d
.asm_a1c
    ld [bc], a
    dec e
    jr nz, .asm_a17
    ret

INCBIN "baserom.gbc",$a21,$b2e - $a21

Func_b2e: ; 0xb2e
    ld hl, $d808
    xor a
    ld [hli], a
    ld [hli], a
    ld [hl], a
    ret

INCBIN "baserom.gbc",$b36,$b66 - $b36

Func_b66: ; 0xb66
    ld a, [$fffe]
    and a
    jr nz, .asm_b73
    xor a
    ld [$ffa3], a
    ld [$ffa4], a
    ld [$ffa5], a
    ret
.asm_b73
    ld de, $ff68
    ld hl, $d200 ; todo
    ld b, $0
    ld c, $20
.asm_b7d
    ld a, b
    ld [$ff68], a
    inc b
    ld a, [$ff69]
    ld [hli], a
    ld a, b
    ld [$ff68], a
    inc b
    ld a, [$ff69]
    ld [hli], a
    dec c
    jr nz, .asm_b7d
    ld b, $0
    ld c, $20
.asm_b92
    ld a, b
    ld [$ff6a], a
    inc b
    ld a, [$ff6b]
    ld [hli], a
    ld a, b
    ld [$ff6a], a
    inc b
    ld a, [$ff6b]
    ld [hli], a
    dec c
    jr nz, .asm_b92
    ld de, $ff68
    ld b, $2
.asm_ba8
    ld a, $80
    ld [de], a
    inc de
    ld c, $20
.asm_bae
    ld a, $ff
    ld [de], a
    ld [hli], a
    ld a, $7f
    ld [de], a
    ld [hli], a
    dec c
    jr nz, .asm_bae
    inc de
    dec b
    jr nz, .asm_ba8
    ret

Func_bbe: ; 0xbbe
    ld a, [$fffe]
    and a
    jp nz, $0c19 ; todo
    ld hl, $ffa3
    ld de, $d80c
    ld b, $3
.asm_bcc
    ld a, [de]
    and $55
    ld c, a
    ld a, [de]
    and $aa
    srl a
    and c
    ld [hli], a
    inc de
    dec b
    jr nz, .asm_bcc
    ld bc, $0002
    call Func_93f
    ld hl, $ffa3
    ld de, $d80c
    ld b, $3
.asm_be9
    ld a, [de]
    and $aa
    srl a
    add [hl]
    ld [hli], a
    inc de
    dec b
    jr nz, .asm_be9
    ld bc, $0002
    call Func_93f
    ld hl, $ffa3
    ld de, $d80c
    ld b, $3
.asm_c02
    ld a, [de]
    and $55
    ld c, a
    ld a, [de]
    and $aa
    srl a
    or c
    add [hl]
    ld [hli], a
    inc de
    dec b
    jr nz, .asm_c02
    ld bc, $0002
    call Func_93f
    ret

Func_c19: ; 0xc19
    ld b, $10
.asm_c1b
    push bc
    ld de, $d200
    ld hl, $d280
    call Func_c2d
    call Func_d61
    pop bc
    dec b
    jr nz, .asm_c1b
    ret

Func_c2d: ; 0xc2d
    ld a, b
    cp $1
    jr z, .asm_c49
    ld c, $40
.asm_c34
    push bc
    ld a, [hli]
    sub $42
    ld c, a
    ld a, [hld]
    sbc $8
    ld b, a
    call Func_c60
    ld a, c
    ld [hli], a
    ld a, b
    ld [hli], a
    pop bc
    dec c
    jr nz, .asm_c34
    ret
.asm_c49
    ld c, $40
.asm_c4b
    push bc
    ld a, [hli]
    sub $21
    ld c, a
    ld a, [hld]
    sbc $4
    ld b, a
    call Func_c60
    ld a, c
    ld [hli], a
    ld a, b
    ld [hli], a
    pop bc
    dec c
    jr nz, .asm_c4b
    ret

Func_c60: ; 0xc60
    push hl
    ld a, [de]
    and $1f
    ld l, a
    ld a, c
    and $1f
    cp l
    jr nc, .asm_c70
    ld a, c
    and $e0
    or l
    ld c, a
.asm_c70
    ld a, [de]
    and $e0
    ld l, a
    inc de
    ld a, [de]
    srl a
    rr l
    srl a
    rr l
    ld a, c
    and $e0
    ld h, a
    ld a, b
    srl a
    rr h
    srl a
    rr h
    ld a, h
    cp l
    jr nc, .asm_ca3
    ld h, $0
    sla l
    rl h
    sla l
    rl h
    ld a, c
    and $1f
    or l
    ld c, a
    ld a, b
    and $7c
    or h
    ld b, a
.asm_ca3
    ld a, [de]
    and $7c
    ld l, a
    ld a, b
    and $7c
    cp l
    jr nc, .asm_cb2
    ld a, b
    and $3
    or l
    ld b, a
.asm_cb2
    inc de
    pop hl
    ret

INCBIN "baserom.gbc",$cb5,$d61 - $cb5

Func_d61: ; 0d61
    ld a, [$ffff]
    res 0, a
    ld [$ffff], a
    ld hl, $d280
    ld de, $ff68
    ld a, $80
    ld [de], a
    inc de
.asm_d71
    ld a, [$ff44]
    cp $90
    jr c, .asm_d71
    ld b, $10
.asm_d79
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    dec b
    jr nz, .asm_d79
    inc de
    ld a, $80
    ld [de], a
    inc de
    ld b, $10
.asm_d8b
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    ld a, [hli]
    ld [de], a
    dec b
    jr nz, .asm_d8b
    ld a, [$ffff]
    set 0, a
    ld [$ffff], a
    ret

INCBIN "baserom.gbc",$d9d,$12a1 - $d9d

Func_12a1: ; 0x12a1
    ld [$fffa], a
    ld a, [$fff8]
    push af
    ld a, [$fffa]
    ld [$fff8], a
    ld [$2000], a
    ld a, [hl]
    and $7
    jr z, .asm_12e5
    ld b, a
    ld c, $0
.asm_12b5
    push bc
    ld a, $0
    ld [$ff00+c], a
    ld a, $30
    ld [$ff00+c], a
    ld b, $10
.asm_12be
    ld e, $8
    ld a, [hli]
    ld d, a
.asm_12c2
    bit 0, d
    ld a, $10
    jr nz, .asm_12ca
    ld a, $20
.asm_12ca
    ld [$ff00+c], a
    ld a, $30
    ld [$ff00+c], a
    rr d
    dec e
    jr nz, .asm_12c2
    dec b
    jr nz, .asm_12be
    ld a, $20
    ld [$ff00+c], a
    ld a, $30
    ld [$ff00+c], a
    pop bc
    dec b
    jr z, .asm_12e5
    call Func_12ec
    jr .asm_12b5
.asm_12e5
    pop af
    ld [$fff8], a
    ld [$2000], a
    ret

Func_12ec ; 0x12ec
    ld de, $1b58
.asm_12ef
    nop
    nop
    nop
    dec de
    ld a, d
    or e
    jr nz, .asm_12ef
    ret

Func_12f8: ; 0x12f8
    ld a, $e
    ld hl, $4010 ; todo
    call Func_12a1
    call Func_12ec
    ld a, [$ff00]
    and $3
    cp $3
    jr nz, .asm_1346
    ld a, $20
    ld [$ff00], a
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, $30
    ld [$ff00], a
    ld a, $10
    ld [$ff00], a
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, $30
    ld [$ff00], a
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    ld a, [$ff00]
    and $3
    cp $3
    jr nz, .asm_1346
    ld a, $e
    ld hl, $4000
    call Func_12a1
    call Func_12ec
    and a
    ret
.asm_1346
    ld a, $e
    ld hl, $4000
    call Func_12a1
    call Func_12ec
    scf
    ret

Func_1353: ; 0x1353
    ld [$fffa], a
    ld a, [$fff8]
    push af
    ld a, [$fffa]
    ld [$fff8], a
    ld [$2000], a
    push af
    push hl
    ld a, $e4
    ld [$ff47], a
    ld de, $0010
    add hl, de
    ld de, $8800 ; bgmap
    call Func_65d
    ld hl, $9800 ; tiles
    ld de, $000c
    ld a, $80
    ld c, $d
.asm_1379
    ld b, $14
.asm_137b
    ld [hli], a
    inc a
    dec b
    jr nz, .asm_137b
    add hl, de
    dec c
    jr nz, .asm_1379
    ld a, $81
    ld [$ff40], a
    ld bc, $0005
    call Func_948
    pop hl
    pop af
    call Func_12a1
    ld bc, $0006
    call Func_948
    ld a, [$ffa3]
    ld [$ff47], a
    ld a, [$ff9e]
    ld [$ff40], a
    pop af
    ld [$fff8], a
    ld [$2000], a
    ret

Func_13a8: ; 0x13a8
    ld a, [$fffb]
    and a
    ret z
    ld bc, $0078
    call Func_948
    call Func_1489
    ld a, $e
    ld hl, $69e6
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $69f6
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a06
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a16
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a26
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a36
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a46
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $6a56
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld bc, $1000
    ld a, $e
    ld hl, $4156 ; todo
    call Func_1353
    ld bc, $0004
    call Func_948
    ld bc, $1000
    ld a, $e
    ld hl, $5166 ; todo
    call Func_1353
    ld bc, $0004
    call Func_948
    ld bc, $0860
    ld a, $e
    ld hl, $6176 ; todo
    call Func_1353
    ld bc, $0004
    call Func_948
    ld bc, $00a0
    ld a, $e
    ld hl, $40a6 ; todo
    call Func_1353
    ld bc, $0004
    call Func_948
    ld bc, $005a
    ld a, $e
    ld hl, $4030
    call Func_1353
    ld bc, $0004
    call Func_948
    ld a, $e
    ld hl, $4020
    call Func_12a1
    ld bc, $0004
    call Func_948
    ret

Func_1489: ; 0x1489
    ld a, [$fffb]
    and a
    ret z
    ld a, [$fffc]
    and a
    ret nz
    ld a, $e
    ld hl, $6a66 ; todo
    call Func_12a1
    ld bc, $0004
    call Func_948
    ld a, $ff
    ld [$fffc], a
    ret

Func_14a4: ; 0x14a4
    ld a, [$fffb]
    and a
    ret z
    ld bc, $0002
    call Func_948
    ld a, [$fffc]
    and a
    ret z
    ld a, $e
    ld hl, $6a76
    call Func_12a1
    ld bc, $0004
    call Func_948
    xor a
    ld [$fffc], a
    ret

INCBIN "baserom.gbc",$14c4,$1ffc - $14c4

Func_1ffc: ; 0x1ffc
    ld a, $b
    ld [$d806], a
    ld a, $4
    ld [$d807], a
    ld [$ff8a], a
    ld a, $f
    ld hl, $4000
    call Func_54f
    ld a, $1
    ld [$d85d], a
    ld a, $37
    ld [$d470], a
    ld [$d471], a
    ld [$d472], a
    ld a, $1
    ld [$d8f1], a
.asm_2025
    call Func_2034
    call Func_2043
    call Func_926
    call Func_b2e
    rst $10
    jr .asm_2025

Func_2034: ; 0x2034
    ld a, [$d804]
    and a
    jr z, .asm_203f
    dec a
    ld [$d804], a
    ret
.asm_203f
    ld [$d803], a
    ret

Func_2043: ; 0x2043
    ld a, [$d8f1]
    call Func_532
    nop
    ld b, b
    ld [bc], a
    nop
    ld e, l
    ld b, c
    ld [bc], a
    nop
    ld e, $42
    ld [bc], a
    nop
    nop
    ld b, b
    inc bc
    nop
    ld d, e
    ld e, b
    inc bc
    nop
    nop
    ld b, b
    ld a, [bc]
    nop
    ld c, d
    ld b, e
    inc bc
    nop
    ld a, a
    ld c, d
    inc bc
    nop
    db $d3
    ld d, [hl]
    inc bc
    nop
    ld a, [$fff8]
    push af
    ld a, $2
    ld [$fff8], a
    ld [$2000], a
    call $4d17 ; todo
    jr c, .asm_2084
    pop af
    ld [$fff8], a
    ld [$2000], a
    and a
    ret
.asm_2084
    pop af
    ld [$fff8], a
    ld [$2000], a
    scf
    ret

INCBIN "baserom.gbc",$208c,$4000 - $208c


SECTION "bank1", ROMX, BANK[$1]

INCBIN "baserom.gbc",$4000,$8000 - $4000 ; 0x4000


SECTION "bank2", ROMX, BANK[$2]

INCBIN "baserom.gbc",$8000,$821e - $8000 ; 0x8000

Func_821e: ; 0x821e
    ld a, [$d8f2]
    rst $18
    jr z, .asm_8266
    sub b
    ld b, d
    xor b
    ld b, d
    ld a, $41
    ld [$ff9e], a
    ld a, $e4
    ld [$d80c], a
    xor a
    ld [$d80d], a
    ld [$d80e], a
    ld [$ffa1], a
    ld [$ffa0], a
    ld a, [$fffe]
    ld hl, .data_825e
    call Func_6a4
    call Func_916
    call Func_b66
    call Func_588
    call Func_14a4
    ld bc, $0050
    call Func_93f
    call Func_bbe
    ld hl, $d8f2
    inc [hl]
    ret

.data_825e
    db $62
    db $42
    db $72
    db $42
    db $0
    db $60
    db $36
    db $0

.asm_8266
INCBIN "baserom.gbc",$8266,$c000 - $8266 ; 0x8266


SECTION "bank3", ROMX, BANK[$3]

INCBIN "baserom.gbc",$c000,$10000 - $c000 ; 0xc000


SECTION "bank4", ROMX, BANK[$4]

INCBIN "baserom.gbc",$10000,$14000 - $10000 ; 0x10000


SECTION "bank5", ROMX, BANK[$5]

INCBIN "baserom.gbc",$14000,$18000 - $14000 ; 0x14000


SECTION "bank6", ROMX, BANK[$6]

INCBIN "baserom.gbc",$18000,$1c000 - $18000 ; 0x18000


SECTION "bank7", ROMX, BANK[$7]

INCBIN "baserom.gbc",$1c000,$20000 - $1c000 ; 0x1c000


SECTION "bank8", ROMX, BANK[$8]

INCBIN "baserom.gbc",$20000,$24000 - $20000 ; 0x20000


SECTION "bank9", ROMX, BANK[$9]

INCBIN "baserom.gbc",$24000,$28000 - $24000 ; 0x24000


SECTION "banka", ROMX, BANK[$a]

INCBIN "baserom.gbc",$28000,$2c000 - $28000 ; 0x28000


SECTION "bankb", ROMX, BANK[$b]

INCBIN "baserom.gbc",$2c000,$30000 - $2c000 ; 0x2c000


SECTION "bankc", ROMX, BANK[$c]

INCBIN "baserom.gbc",$30000,$33fff - $30000 ; 0x30000


SECTION "bankd", ROMX, BANK[$d]

SlotOnPic: ; 0x34000
	INCBIN "gfx/billboard/slot/slot_on.2bpp"
SlotOffPic: ; 0x34180
	INCBIN "gfx/billboard/slot/slot_off.2bpp"

INCBIN "baserom.gbc",$34300,$38000 - $34300 ; 0x34000


SECTION "banke", ROMX, BANK[$e]

INCBIN "baserom.gbc",$38000,$3c000 - $38000 ; 0x38000


SECTION "bankf", ROMX, BANK[$f]

INCBIN "baserom.gbc",$3c000,$40000 - $3c000 ; 0x3c000


SECTION "bank10", ROMX, BANK[$10]

INCBIN "baserom.gbc",$40000,$44000 - $40000 ; 0x40000


SECTION "bank11", ROMX, BANK[$11]

INCBIN "baserom.gbc",$44000,$48000 - $44000 ; 0x44000


SECTION "bank12", ROMX, BANK[$12]

INCBIN "baserom.gbc",$48000,$4c000 - $48000 ; 0x48000


SECTION "bank13", ROMX, BANK[$13]

INCBIN "baserom.gbc",$4c000,$50000 - $4c000 ; 0x4c000


SECTION "bank14", ROMX, BANK[$14]

INCBIN "baserom.gbc",$50000,$54000 - $50000 ; 0x50000


SECTION "bank15", ROMX, BANK[$15]

INCBIN "baserom.gbc",$54000,$58000 - $54000 ; 0x54000


SECTION "bank16", ROMX, BANK[$16]

BallSaver30SecondsOnPic: ; 0x58000
	INCBIN "gfx/billboard/slot/30secondballsaver_on.2bpp"
BallSaver30SecondsOffPic: ; 0x58180
	INCBIN "gfx/billboard/slot/30secondballsaver_off.2bpp"
BallSaver60SecondsOnPic: ; 0x58300
	INCBIN "gfx/billboard/slot/60secondballsaver_on.2bpp"
BallSaver60SecondsOffPic: ; 0x580480
	INCBIN "gfx/billboard/slot/60secondballsaver_off.2bpp"
BallSaver90SecondsOnPic: ; 0x58600
	INCBIN "gfx/billboard/slot/90secondballsaver_on.2bpp"
BallSaver90SecondsOffPic: ; 0x58780
	INCBIN "gfx/billboard/slot/90secondballsaver_off.2bpp"
PikachuSaverOnPic: ; 0x58900
	INCBIN "gfx/billboard/slot/pikachusaver_on.2bpp"
PikachuSaverOffPic: ; 0x58a80
	INCBIN "gfx/billboard/slot/pikachusaver_off.2bpp"
ExtraBallOnPic: ; 0x58c00
	INCBIN "gfx/billboard/slot/extraball_on.2bpp"
ExtraBallOffPic: ; 0x58d80
	INCBIN "gfx/billboard/slot/extraball_off.2bpp"
SmallRewardOnPic: ; 0x58f00
	INCBIN "gfx/billboard/slot/small_on.2bpp"
SmallRewardOffPic: ; 0x59080
	INCBIN "gfx/billboard/slot/small_off.2bpp"
BigRewardOnPic: ; 0x59200
	INCBIN "gfx/billboard/slot/big_on.2bpp"
BigRewardOffPic: ; 0x59380
	INCBIN "gfx/billboard/slot/big_off.2bpp"
CatchEmModeOnPic: ; 0x59500
	INCBIN "gfx/billboard/slot/catchem_on.2bpp"
CatchEmModeOffPic: ; 0x59680
	INCBIN "gfx/billboard/slot/catchem_off.2bpp"
EvolutionModeOnPic: ; 0x59800
	INCBIN "gfx/billboard/slot/evolution_on.2bpp"
EvolutionModeOffPic: ; 0x59980
	INCBIN "gfx/billboard/slot/evolution_off.2bpp"
GreatBallOnPic: ; 0x59b00
	INCBIN "gfx/billboard/slot/greatball_on.2bpp"
GreatBallOffPic: ; 0x59c80
	INCBIN "gfx/billboard/slot/greatball_off.2bpp"
UltraBallOnPic: ; 0x59e00
	INCBIN "gfx/billboard/slot/ultraball_on.2bpp"
UltraBallOffPic: ; 0x59f80
	INCBIN "gfx/billboard/slot/ultraball_off.2bpp"
MasterBallOnPic: ; 0x5a100
	INCBIN "gfx/billboard/slot/masterball_on.2bpp"
MasterBallOffPic: ; 0x5a280
	INCBIN "gfx/billboard/slot/masterball_off.2bpp"
BonusMultiplierOnPic: ; 0x5a400
	INCBIN "gfx/billboard/slot/bonusmultiplier_on.2bpp"
BonusMultiplierOffPic: ; 0x5a580
	INCBIN "gfx/billboard/slot/bonusmultiplier_off.2bpp"
HurryUpOnPic: ; 0x5a700
	INCBIN "gfx/billboard/hurryup_on.2bpp"
HurryUpOffPic: ; 0x5a880
	INCBIN "gfx/billboard/hurryup_off.2bpp"
HurryUp2OnPic: ; 0x5aa00
	INCBIN "gfx/billboard/hurryup2_on.2bpp"
HurryUp2OffPic: ; 0x5ab80
	INCBIN "gfx/billboard/hurryup2_off.2bpp"
GoToNextOnPic: ; 0x5ad00
	INCBIN "gfx/billboard/gotonext_on.2bpp"
GoToNextOffPic: ; 0x5ae80
	INCBIN "gfx/billboard/gotonext_off.2bpp"
GoToGengarBonusOnPic: ; 0x5b000
	INCBIN "gfx/billboard/bonus_stages/gotogengarbonus_on.2bpp"
GoToGengarBonusOffPic: ; 0x5b180
	INCBIN "gfx/billboard/bonus_stages/gotogengarbonus_off.2bpp"
GoToMewtwoBonusOnPic: ; 0x5b300
	INCBIN "gfx/billboard/bonus_stages/gotomewtwobonus_on.2bpp"
GoToMewtwoBonusOffPic: ; 0x5b480
	INCBIN "gfx/billboard/bonus_stages/gotomewtwobonus_off.2bpp"
GoToMeowthBonusOnPic: ; 0x5b600
	INCBIN "gfx/billboard/bonus_stages/gotomeowthbonus_on.2bpp"
GoToMeowthBonusOffPic: ; 0x5b780
	INCBIN "gfx/billboard/bonus_stages/gotomeowthbonus_off.2bpp"
GoToDiglettBonusOnPic: ; 0x5b900
	INCBIN "gfx/billboard/bonus_stages/gotodiglettbonus_on.2bpp"
GoToDiglettBonusOffPic: ; 0x5ba80
	INCBIN "gfx/billboard/bonus_stages/gotodiglettbonus_off.2bpp"
GoToSeelBonusOnPic: ; 0x5bc00
	INCBIN "gfx/billboard/bonus_stages/gotoseelbonus_on.2bpp"
GoToSeelBonusOffPic: ; 0x5bd80
	INCBIN "gfx/billboard/bonus_stages/gotoseelbonus_off.2bpp"

INCBIN "baserom.gbc",$5bf00,$5c000 - $5bf00 ; 0x5bf00


SECTION "bank17", ROMX, BANK[$17]

SmallReward100PointsOnPic: ; 0x5c000
	INCBIN "gfx/billboard/slot/100points_on.2bpp"
SmallReward100PointsOffPic: ; 0x5c180
	INCBIN "gfx/billboard/slot/100points_off.2bpp"
SmallReward200PointsOnPic: ; 0x5c300
	INCBIN "gfx/billboard/slot/200points_on.2bpp"
SmallReward200PointsOffPic: ; 0x54800
	INCBIN "gfx/billboard/slot/200points_off.2bpp"
SmallReward300PointsOnPic: ; 0x5c600
	INCBIN "gfx/billboard/slot/300points_on.2bpp"
SmallReward300PointsOffPic: ; 0x5c780
	INCBIN "gfx/billboard/slot/300points_off.2bpp"
SmallReward400PointsOnPic: ; 0x5c900
	INCBIN "gfx/billboard/slot/400points_on.2bpp"
SmallReward400PointsOffPic: ; 0x5ca80
	INCBIN "gfx/billboard/slot/400points_off.2bpp"
SmallReward500PointsOnPic: ; 0x5cc00
	INCBIN "gfx/billboard/slot/500points_on.2bpp"
SmallReward500PointsOffPic: ; 0x5cd80
	INCBIN "gfx/billboard/slot/500points_off.2bpp"
SmallReward600PointsOnPic: ; 0x5cf00
	INCBIN "gfx/billboard/slot/600points_on.2bpp"
SmallReward600PointsOffPic: ; 0x5d080
	INCBIN "gfx/billboard/slot/600points_off.2bpp"
SmallReward700PointsOnPic: ; 0x5d200
	INCBIN "gfx/billboard/slot/700points_on.2bpp"
SmallReward700PointsOffPic: ; 0x5d380
	INCBIN "gfx/billboard/slot/700points_off.2bpp"
SmallReward800PointsOnPic: ; 0x5d500
	INCBIN "gfx/billboard/slot/800points_on.2bpp"
SmallReward800PointsOffPic: ; 0x5d680
	INCBIN "gfx/billboard/slot/800points_off.2bpp"
SmallReward900PointsOnPic: ; 0x5d800
	INCBIN "gfx/billboard/slot/900points_on.2bpp"
SmallReward900PointsOffPic: ; 0x5d980
	INCBIN "gfx/billboard/slot/900points_off.2bpp"
BigReward1000000PointsOnPic: ; 0x5db00
	INCBIN "gfx/billboard/slot/1000000points_on.2bpp"
BigReward1000000PointsOffPic: ; 0x5dc80
	INCBIN "gfx/billboard/slot/1000000points_off.2bpp"
BigReward2000000PointsOnPic: ; 0x5de00
	INCBIN "gfx/billboard/slot/2000000points_on.2bpp"
BigReward2000000PointsOffPic: ; 0x5df80
	INCBIN "gfx/billboard/slot/2000000points_off.2bpp"
BigReward3000000PointsOnPic: ; 0x5e100
	INCBIN "gfx/billboard/slot/3000000points_on.2bpp"
BigReward3000000PointsOffPic: ; 0x5e280
	INCBIN "gfx/billboard/slot/3000000points_off.2bpp"
BigReward4000000PointsOnPic: ; 0x5e400
	INCBIN "gfx/billboard/slot/4000000points_on.2bpp"
BigReward4000000PointsOffPic: ; 0x5e580
	INCBIN "gfx/billboard/slot/4000000points_off.2bpp"
BigReward5000000PointsOnPic: ; 0x5e700
	INCBIN "gfx/billboard/slot/5000000points_on.2bpp"
BigReward5000000PointsOffPic: ; 0x5e880
	INCBIN "gfx/billboard/slot/5000000points_off.2bpp"
BigReward6000000PointsOnPic: ; 0x5ea00
	INCBIN "gfx/billboard/slot/6000000points_on.2bpp"
BigReward6000000PointsOffPic: ; 0x5eb80
	INCBIN "gfx/billboard/slot/6000000points_off.2bpp"
BigReward7000000PointsOnPic: ; 0x5ed00
	INCBIN "gfx/billboard/slot/7000000points_on.2bpp"
BigReward7000000PointsOffPic: ; 0x5ee80
	INCBIN "gfx/billboard/slot/7000000points_off.2bpp"
BigReward8000000PointsOnPic: ; 0x5f000
	INCBIN "gfx/billboard/slot/8000000points_on.2bpp"
BigReward8000000PointsOffPic: ; 0x5f180
	INCBIN "gfx/billboard/slot/8000000points_off.2bpp"
BigReward9000000PointsOnPic: ; 0x5f300
	INCBIN "gfx/billboard/slot/9000000points_on.2bpp"
BigReward9000000PointsOffPic: ; 0x5f480
	INCBIN "gfx/billboard/slot/9000000points_off.2bpp"

INCBIN "baserom.gbc",$5f600,$60000 - $5f600 ; 0x5f600


SECTION "bank18", ROMX, BANK[$18]

VenomothPic: ; 0x60000
	INCBIN "gfx/billboard/mon_pics/venomoth.2bpp"
VenomothSilhouettePic: ; 0x60180
	INCBIN "gfx/billboard/mon_silhouettes/venomoth.2bpp"
DiglettPic: ; 0x60300
	INCBIN "gfx/billboard/mon_pics/diglett.2bpp"
DiglettSilhouettePic: ; 0x60480
	INCBIN "gfx/billboard/mon_silhouettes/diglett.2bpp"
DugtrioPic: ; 0x60600
	INCBIN "gfx/billboard/mon_pics/dugtrio.2bpp"
DugtrioSilhouettePic: ; 0x60780
	INCBIN "gfx/billboard/mon_silhouettes/dugtrio.2bpp"
MeowthPic: ; 0x60900
	INCBIN "gfx/billboard/mon_pics/meowth.2bpp"
MeowthSilhouettePic: ; 0x60a80
	INCBIN "gfx/billboard/mon_silhouettes/meowth.2bpp"
PersianPic: ; 0x60c00
	INCBIN "gfx/billboard/mon_pics/persian.2bpp"
PersianSilhouettePic: ; 0x60d80
	INCBIN "gfx/billboard/mon_silhouettes/persian.2bpp"
PsyduckPic: ; 0x60f00
	INCBIN "gfx/billboard/mon_pics/psyduck.2bpp"
PsyduckSilhouettePic: ; 0x61080
	INCBIN "gfx/billboard/mon_silhouettes/psyduck.2bpp"
GolduckPic: ; 0x61200
	INCBIN "gfx/billboard/mon_pics/golduck.2bpp"
GolduckSilhouettePic:  ; 0x61380
	INCBIN "gfx/billboard/mon_silhouettes/golduck.2bpp"
MankeyPic: ; 0x61500
	INCBIN "gfx/billboard/mon_pics/mankey.2bpp"
MankeySilhouettePic: ; 0x61680
	INCBIN "gfx/billboard/mon_silhouettes/mankey.2bpp"
PrimeapePic: ; 0x61800
	INCBIN "gfx/billboard/mon_pics/primeape.2bpp"
PrimeapeSilhouettePic: ; 0x61980
	INCBIN "gfx/billboard/mon_silhouettes/primeape.2bpp"
GrowlithePic: ; 0x61b00
	INCBIN "gfx/billboard/mon_pics/growlithe.2bpp"
GrowlitheSilhouettePic: ; 0x61c80
	INCBIN "gfx/billboard/mon_silhouettes/growlithe.2bpp"
ArcaninePic: ; 0x61e00
	INCBIN "gfx/billboard/mon_pics/arcanine.2bpp"
ArcanineSilhouettePic: ; 0x61f80
	INCBIN "gfx/billboard/mon_silhouettes/arcanine.2bpp"
PoliwagPic: ; 0x62100
	INCBIN "gfx/billboard/mon_pics/poliwag.2bpp"
PoliwagSilhouettePic: ; 0x62280
	INCBIN "gfx/billboard/mon_silhouettes/poliwag.2bpp"
PoliwhirlPic: ; 0x62400
	INCBIN "gfx/billboard/mon_pics/poliwhirl.2bpp"
PoliwhirlSilhouettePic: ; 0x62580
	INCBIN "gfx/billboard/mon_silhouettes/poliwhirl.2bpp"
PoliwrathPic: ; 0x62700
	INCBIN "gfx/billboard/mon_pics/poliwrath.2bpp"
PoliwrathSilhouettePic: ; 0x62880
	INCBIN "gfx/billboard/mon_silhouettes/poliwrath.2bpp"
AbraPic: ; 0x62a00
	INCBIN "gfx/billboard/mon_pics/abra.2bpp"
AbraSilhouettePic: ; 0x62b80
	INCBIN "gfx/billboard/mon_silhouettes/abra.2bpp"
KadabraPic: ; 0x62d00
	INCBIN "gfx/billboard/mon_pics/kadabra.2bpp"
KadabraSilhouettePic: ; 0x62e80
	INCBIN "gfx/billboard/mon_silhouettes/kadabra.2bpp"

INCBIN "baserom.gbc",$63000,$64000 - $63000 ; 0x63000


SECTION "bank19", ROMX, BANK[$19]

NidorinoPic: ; 0x64000
	INCBIN "gfx/billboard/mon_pics/nidorino.2bpp"
NidorinoSilhouettePic: ; 0x64180
	INCBIN "gfx/billboard/mon_silhouettes/nidorino.2bpp"
NidokingPic: ; 0x64300
	INCBIN "gfx/billboard/mon_pics/nidoking.2bpp"
NidokingSilhouettePic: ; 0x64480
	INCBIN "gfx/billboard/mon_silhouettes/nidoking.2bpp"
ClefairyPic: ; 0x64600
	INCBIN "gfx/billboard/mon_pics/clefairy.2bpp"
ClefairySilhouettePic: ; 0x64780
	INCBIN "gfx/billboard/mon_silhouettes/clefairy.2bpp"
ClefablePic: ; 0x64900
	INCBIN "gfx/billboard/mon_pics/clefable.2bpp"
ClefableSilhouettePic: ; 0x64a80
	INCBIN "gfx/billboard/mon_silhouettes/clefable.2bpp"
VulpixPic: ; 0x64c00
	INCBIN "gfx/billboard/mon_pics/vulpix.2bpp"
VulpixSilhouettePic: ; 0x64d80
	INCBIN "gfx/billboard/mon_silhouettes/vulpix.2bpp"
NinetalesPic: ; 0x64f00
	INCBIN "gfx/billboard/mon_pics/ninetales.2bpp"
NinetalesSilhouettePic: ; 0x65080
	INCBIN "gfx/billboard/mon_silhouettes/ninetales.2bpp"
JigglypuffPic: ; 0x65200
	INCBIN "gfx/billboard/mon_pics/jigglypuff.2bpp"
JigglypuffSilhouettePic:  ; 0x65380
	INCBIN "gfx/billboard/mon_silhouettes/jigglypuff.2bpp"
WigglytuffPic: ; 0x65500
	INCBIN "gfx/billboard/mon_pics/wigglytuff.2bpp"
WigglytuffSilhouettePic: ; 0x65680
	INCBIN "gfx/billboard/mon_silhouettes/wigglytuff.2bpp"
ZubatPic: ; 0x65800
	INCBIN "gfx/billboard/mon_pics/zubat.2bpp"
ZubatSilhouettePic: ; 0x65980
	INCBIN "gfx/billboard/mon_silhouettes/zubat.2bpp"
GolbatPic: ; 0x65b00
	INCBIN "gfx/billboard/mon_pics/golbat.2bpp"
GolbatSilhouettePic: ; 0x65c80
	INCBIN "gfx/billboard/mon_silhouettes/golbat.2bpp"
OddishPic: ; 0x65e00
	INCBIN "gfx/billboard/mon_pics/oddish.2bpp"
OddishSilhouettePic: ; 0x65f80
	INCBIN "gfx/billboard/mon_silhouettes/oddish.2bpp"
GloomPic: ; 0x66100
	INCBIN "gfx/billboard/mon_pics/gloom.2bpp"
GloomSilhouettePic: ; 0x66280
	INCBIN "gfx/billboard/mon_silhouettes/gloom.2bpp"
VileplumePic: ; 0x66400
	INCBIN "gfx/billboard/mon_pics/vileplume.2bpp"
VileplumeSilhouettePic: ; 0x66580
	INCBIN "gfx/billboard/mon_silhouettes/vileplume.2bpp"
ParasPic: ; 0x66700
	INCBIN "gfx/billboard/mon_pics/paras.2bpp"
ParasSilhouettePic: ; 0x66880
	INCBIN "gfx/billboard/mon_silhouettes/paras.2bpp"
ParasectPic: ; 0x66a00
	INCBIN "gfx/billboard/mon_pics/parasect.2bpp"
ParasectSilhouettePic: ; 0x66b80
	INCBIN "gfx/billboard/mon_silhouettes/parasect.2bpp"
VenonatPic: ; 0x66d00
	INCBIN "gfx/billboard/mon_pics/venonat.2bpp"
VenonatSilhouettePic: ; 0x66e80
	INCBIN "gfx/billboard/mon_silhouettes/venonat.2bpp"

INCBIN "baserom.gbc",$67000,$68000 - $67000 ; 0x67000


SECTION "bank1a", ROMX, BANK[$1a]

ChanseyPic: ; 0x68000
	INCBIN "gfx/billboard/mon_pics/chansey.2bpp"
ChanseySilhouettePic: ; 0x68180
	INCBIN "gfx/billboard/mon_silhouettes/chansey.2bpp"
TangelaPic: ; 0x68300
	INCBIN "gfx/billboard/mon_pics/tangela.2bpp"
TangelaSilhouettePic: ; 0x68480
	INCBIN "gfx/billboard/mon_silhouettes/tangela.2bpp"
KangaskhanPic: ; 0x68600
	INCBIN "gfx/billboard/mon_pics/kangaskhan.2bpp"
KangaskhanSilhouettePic: ; 0x68780
	INCBIN "gfx/billboard/mon_silhouettes/kangaskhan.2bpp"
HorseaPic: ; 0x68900
	INCBIN "gfx/billboard/mon_pics/horsea.2bpp"
HorseaSilhouettePic: ; 0x68a80
	INCBIN "gfx/billboard/mon_silhouettes/horsea.2bpp"
SeadraPic: ; 0x68c00
	INCBIN "gfx/billboard/mon_pics/seadra.2bpp"
SeadraSilhouettePic: ; 0x68d80
	INCBIN "gfx/billboard/mon_silhouettes/seadra.2bpp"
GoldeenPic: ; 0x68f00
	INCBIN "gfx/billboard/mon_pics/goldeen.2bpp"
GoldeenSilhouettePic: ; 0x69080
	INCBIN "gfx/billboard/mon_silhouettes/goldeen.2bpp"
SeakingPic: ; 0x69200
	INCBIN "gfx/billboard/mon_pics/seaking.2bpp"
SeakingSilhouettePic:  ; 0x69380
	INCBIN "gfx/billboard/mon_silhouettes/seaking.2bpp"
StaryuPic: ; 0x69500
	INCBIN "gfx/billboard/mon_pics/staryu.2bpp"
StaryuSilhouettePic: ; 0x69680
	INCBIN "gfx/billboard/mon_silhouettes/staryu.2bpp"
StarmiePic: ; 0x69800
	INCBIN "gfx/billboard/mon_pics/starmie.2bpp"
StarmieSilhouettePic: ; 0x69980
	INCBIN "gfx/billboard/mon_silhouettes/starmie.2bpp"
Mr_MimePic: ; 0x69b00
	INCBIN "gfx/billboard/mon_pics/mr_mime.2bpp"
Mr_MimeSilhouettePic: ; 0x69c80
	INCBIN "gfx/billboard/mon_silhouettes/mr_mime.2bpp"
ScytherPic: ; 0x69e00
	INCBIN "gfx/billboard/mon_pics/scyther.2bpp"
ScytherSilhouettePic: ; 0x69f80
	INCBIN "gfx/billboard/mon_silhouettes/scyther.2bpp"
JynxPic: ; 0x6a100
	INCBIN "gfx/billboard/mon_pics/jynx.2bpp"
JynxSilhouettePic: ; 0x6a280
	INCBIN "gfx/billboard/mon_silhouettes/jynx.2bpp"
ElectabuzzPic: ; 0x6a400
	INCBIN "gfx/billboard/mon_pics/electabuzz.2bpp"
ElectabuzzSilhouettePic: ; 0x6a580
	INCBIN "gfx/billboard/mon_silhouettes/electabuzz.2bpp"
MagmarPic: ; 0x6a700
	INCBIN "gfx/billboard/mon_pics/magmar.2bpp"
MagmarSilhouettePic: ; 0x6a880
	INCBIN "gfx/billboard/mon_silhouettes/magmar.2bpp"
PinsirPic: ; 0x6aa00
	INCBIN "gfx/billboard/mon_pics/pinsir.2bpp"
PinsirSilhouettePic: ; 0x6ab80
	INCBIN "gfx/billboard/mon_silhouettes/pinsir.2bpp"
TaurosPic: ; 0x6ad00
	INCBIN "gfx/billboard/mon_pics/tauros.2bpp"
TaurosSilhouettePic: ; 0x6ae80
	INCBIN "gfx/billboard/mon_silhouettes/tauros.2bpp"

INCBIN "baserom.gbc",$6b000,$6c000 - $6b000 ; 0x6b000


SECTION "bank1b", ROMX, BANK[$1b]

MagikarpPic: ; 0x6c000
	INCBIN "gfx/billboard/mon_pics/magikarp.2bpp"
MagikarpSilhouettePic: ; 0x6c180
	INCBIN "gfx/billboard/mon_silhouettes/magikarp.2bpp"
GyaradosPic: ; 0x6c300
	INCBIN "gfx/billboard/mon_pics/gyarados.2bpp"
GyaradosSilhouettePic: ; 0x6c480
	INCBIN "gfx/billboard/mon_silhouettes/gyarados.2bpp"
LaprasPic: ; 0x6c600
	INCBIN "gfx/billboard/mon_pics/lapras.2bpp"
LaprasSilhouettePic: ; 0x6c780
	INCBIN "gfx/billboard/mon_silhouettes/lapras.2bpp"
DittoPic: ; 0x6c900
	INCBIN "gfx/billboard/mon_pics/ditto.2bpp"
DittoSilhouettePic: ; 0x6ca80
	INCBIN "gfx/billboard/mon_silhouettes/ditto.2bpp"
EeveePic: ; 0x6cc00
	INCBIN "gfx/billboard/mon_pics/eevee.2bpp"
EeveeSilhouettePic: ; 0x6cd80
	INCBIN "gfx/billboard/mon_silhouettes/eevee.2bpp"
VaporeonPic: ; 0x6cf00
	INCBIN "gfx/billboard/mon_pics/vaporeon.2bpp"
VaporeonSilhouettePic: ; 0x6d080
	INCBIN "gfx/billboard/mon_silhouettes/vaporeon.2bpp"
JolteonPic: ; 0x6d200
	INCBIN "gfx/billboard/mon_pics/jolteon.2bpp"
JolteonSilhouettePic:  ; 0x6d380
	INCBIN "gfx/billboard/mon_silhouettes/jolteon.2bpp"
FlareonPic: ; 0x6d500
	INCBIN "gfx/billboard/mon_pics/flareon.2bpp"
FlareonSilhouettePic: ; 0x6d680
	INCBIN "gfx/billboard/mon_silhouettes/flareon.2bpp"
PorygonPic: ; 0x6d800
	INCBIN "gfx/billboard/mon_pics/porygon.2bpp"
PorygonSilhouettePic: ; 0x6d980
	INCBIN "gfx/billboard/mon_silhouettes/porygon.2bpp"
OmanytePic: ; 0x6db00
	INCBIN "gfx/billboard/mon_pics/omanyte.2bpp"
OmanyteSilhouettePic: ; 0x6dc80
	INCBIN "gfx/billboard/mon_silhouettes/omanyte.2bpp"
OmastarPic: ; 0x6de00
	INCBIN "gfx/billboard/mon_pics/omastar.2bpp"
OmastarSilhouettePic: ; 0x6df80
	INCBIN "gfx/billboard/mon_silhouettes/omastar.2bpp"
KabutoPic: ; 0x6e100
	INCBIN "gfx/billboard/mon_pics/kabuto.2bpp"
KabutoSilhouettePic: ; 0x6e280
	INCBIN "gfx/billboard/mon_silhouettes/kabuto.2bpp"
KabutopsPic: ; 0x6e400
	INCBIN "gfx/billboard/mon_pics/kabutops.2bpp"
KabutopsSilhouettePic: ; 0x6e580
	INCBIN "gfx/billboard/mon_silhouettes/kabutops.2bpp"
AerodactylPic: ; 0x6e700
	INCBIN "gfx/billboard/mon_pics/aerodactyl.2bpp"
AerodactylSilhouettePic: ; 0x6e880
	INCBIN "gfx/billboard/mon_silhouettes/aerodactyl.2bpp"
SnorlaxPic: ; 0x6ea00
	INCBIN "gfx/billboard/mon_pics/snorlax.2bpp"
SnorlaxSilhouettePic: ; 0x6eb80
	INCBIN "gfx/billboard/mon_silhouettes/snorlax.2bpp"
ArticunoPic: ; 0x6ed00
	INCBIN "gfx/billboard/mon_pics/articuno.2bpp"
ArticunoSilhouettePic: ; 0x6ee80
	INCBIN "gfx/billboard/mon_silhouettes/articuno.2bpp"

INCBIN "baserom.gbc",$6f000,$70000 - $6f000 ; 0x6f000


SECTION "bank1c", ROMX, BANK[$1c]

ZapdosPic: ; 0x70000
	INCBIN "gfx/billboard/mon_pics/zapdos.2bpp"
ZapdosSilhouettePic: ; 0x70180
	INCBIN "gfx/billboard/mon_silhouettes/zapdos.2bpp"
MoltresPic: ; 0x70300
	INCBIN "gfx/billboard/mon_pics/moltres.2bpp"
MoltresSilhouettePic: ; 0x70480
	INCBIN "gfx/billboard/mon_silhouettes/moltres.2bpp"
DratiniPic: ; 0x70600
	INCBIN "gfx/billboard/mon_pics/dratini.2bpp"
DratiniSilhouettePic: ; 0x70780
	INCBIN "gfx/billboard/mon_silhouettes/dratini.2bpp"
DragonairPic: ; 0x70900
	INCBIN "gfx/billboard/mon_pics/dragonair.2bpp"
DragonairSilhouettePic: ; 0x70a80
	INCBIN "gfx/billboard/mon_silhouettes/dragonair.2bpp"
DragonitePic: ; 0x70c00
	INCBIN "gfx/billboard/mon_pics/dragonite.2bpp"
DragoniteSilhouettePic: ; 0x70d80
	INCBIN "gfx/billboard/mon_silhouettes/dragonite.2bpp"
MewtwoPic: ; 0x70f00
	INCBIN "gfx/billboard/mon_pics/mewtwo.2bpp"
MewtwoSilhouettePic: ; 0x71080
	INCBIN "gfx/billboard/mon_silhouettes/mewtwo.2bpp"
MewPic: ; 0x71200
	INCBIN "gfx/billboard/mon_pics/mew.2bpp"
MewSilhouettePic:  ; 0x71380
	INCBIN "gfx/billboard/mon_silhouettes/mew.2bpp"

INCBIN "baserom.gbc",$71500,$74000 - $71500 ; 0x71500


SECTION "bank1d", ROMX, BANK[$1d]

PidgeottoPic: ; 0x74000
	INCBIN "gfx/billboard/mon_pics/pidgeotto.2bpp"
PidgeottoSilhouettePic: ; 0x74180
	INCBIN "gfx/billboard/mon_silhouettes/pidgeotto.2bpp"
PidgeotPic: ; 0x74300
	INCBIN "gfx/billboard/mon_pics/pidgeot.2bpp"
PidgeotSilhouettePic: ; 0x74480
	INCBIN "gfx/billboard/mon_silhouettes/pidgeot.2bpp"
RattataPic: ; 0x74600
	INCBIN "gfx/billboard/mon_pics/rattata.2bpp"
RattataSilhouettePic: ; 0x74780
	INCBIN "gfx/billboard/mon_silhouettes/rattata.2bpp"
RaticatePic: ; 0x74900
	INCBIN "gfx/billboard/mon_pics/raticate.2bpp"
RaticateSilhouettePic: ; 0x74a80
	INCBIN "gfx/billboard/mon_silhouettes/raticate.2bpp"
SpearowPic: ; 0x74c00
	INCBIN "gfx/billboard/mon_pics/spearow.2bpp"
SpearowSilhouettePic: ; 0x74d80
	INCBIN "gfx/billboard/mon_silhouettes/spearow.2bpp"
FearowPic: ; 0x74f00
	INCBIN "gfx/billboard/mon_pics/fearow.2bpp"
FearowSilhouettePic: ; 0x75080
	INCBIN "gfx/billboard/mon_silhouettes/fearow.2bpp"
EkansPic: ; 0x75200
	INCBIN "gfx/billboard/mon_pics/ekans.2bpp"
EkansSilhouettePic:  ; 0x75380
	INCBIN "gfx/billboard/mon_silhouettes/ekans.2bpp"
ArbokPic: ; 0x75500
	INCBIN "gfx/billboard/mon_pics/arbok.2bpp"
ArbokSilhouettePic: ; 0x75680
	INCBIN "gfx/billboard/mon_silhouettes/arbok.2bpp"
PikachuPic: ; 0x75800
	INCBIN "gfx/billboard/mon_pics/pikachu.2bpp"
PikachuSilhouettePic: ; 0x75980
	INCBIN "gfx/billboard/mon_silhouettes/pikachu.2bpp"
RaichuPic: ; 0x75b00
	INCBIN "gfx/billboard/mon_pics/raichu.2bpp"
RaichuSilhouettePic: ; 0x75c80
	INCBIN "gfx/billboard/mon_silhouettes/raichu.2bpp"
SandshrewPic: ; 0x75e00
	INCBIN "gfx/billboard/mon_pics/sandshrew.2bpp"
SandshrewSilhouettePic: ; 0x75f80
	INCBIN "gfx/billboard/mon_silhouettes/sandshrew.2bpp"
SandslashPic: ; 0x76100
	INCBIN "gfx/billboard/mon_pics/sandslash.2bpp"
SandslashSilhouettePic: ; 0x76280
	INCBIN "gfx/billboard/mon_silhouettes/sandslash.2bpp"
Nidoran_FPic: ; 0x76400
	INCBIN "gfx/billboard/mon_pics/nidoran_f.2bpp"
Nidoran_FSilhouettePic: ; 0x76580
	INCBIN "gfx/billboard/mon_silhouettes/nidoran_f.2bpp"
NidorinaPic: ; 0x76700
	INCBIN "gfx/billboard/mon_pics/nidorina.2bpp"
NidorinaSilhouettePic: ; 0x76880
	INCBIN "gfx/billboard/mon_silhouettes/nidorina.2bpp"
NidoqueenPic: ; 0x76a00
	INCBIN "gfx/billboard/mon_pics/nidoqueen.2bpp"
NidoqueenSilhouettePic: ; 0x76b80
	INCBIN "gfx/billboard/mon_silhouettes/nidoqueen.2bpp"
Nidoran_MPic: ; 0x76d00
	INCBIN "gfx/billboard/mon_pics/nidoran_m.2bpp"
Nidoran_MSilhouettePic: ; 0x76e80
	INCBIN "gfx/billboard/mon_silhouettes/nidoran_m.2bpp"

INCBIN "baserom.gbc",$77000,$78000 - $77000 ; 0x77000


SECTION "bank1e", ROMX, BANK[$1e]

BulbasaurPic: ; 0x78000
	INCBIN "gfx/billboard/mon_pics/bulbasaur.2bpp"
BulbasaurSilhouettePic: ; 0x78180
	INCBIN "gfx/billboard/mon_silhouettes/bulbasaur.2bpp"
IvysaurPic: ; 0x78300
	INCBIN "gfx/billboard/mon_pics/ivysaur.2bpp"
IvysaurSilhouettePic: ; 0x78480
	INCBIN "gfx/billboard/mon_silhouettes/ivysaur.2bpp"
VenusaurPic: ; 0x78600
	INCBIN "gfx/billboard/mon_pics/venusaur.2bpp"
VenusaurSilhouettePic: ; 0x78780
	INCBIN "gfx/billboard/mon_silhouettes/venusaur.2bpp"
CharmanderPic: ; 0x78900
	INCBIN "gfx/billboard/mon_pics/charmander.2bpp"
CharmanderSilhouettePic: ; 0x78a80
	INCBIN "gfx/billboard/mon_silhouettes/charmander.2bpp"
CharmeleonPic: ; 0x78c00
	INCBIN "gfx/billboard/mon_pics/charmeleon.2bpp"
CharmeleonSilhouettePic: ; 0x78d80
	INCBIN "gfx/billboard/mon_silhouettes/charmeleon.2bpp"
CharizardPic: ; 0x78f00
	INCBIN "gfx/billboard/mon_pics/charizard.2bpp"
CharizardSilhouettePic: ; 0x79080
	INCBIN "gfx/billboard/mon_silhouettes/charizard.2bpp"
SquirtlePic: ; 0x79200
	INCBIN "gfx/billboard/mon_pics/squirtle.2bpp"
SquirtleSilhouettePic:  ; 0x79380
	INCBIN "gfx/billboard/mon_silhouettes/squirtle.2bpp"
WartortlePic: ; 0x79500
	INCBIN "gfx/billboard/mon_pics/wartortle.2bpp"
WartortleSilhouettePic: ; 0x79680
	INCBIN "gfx/billboard/mon_silhouettes/wartortle.2bpp"
BlastoisePic: ; 0x79800
	INCBIN "gfx/billboard/mon_pics/blastoise.2bpp"
BlastoiseSilhouettePic: ; 0x79980
	INCBIN "gfx/billboard/mon_silhouettes/blastoise.2bpp"
CaterpiePic: ; 0x79b00
	INCBIN "gfx/billboard/mon_pics/caterpie.2bpp"
CaterpieSilhouettePic: ; 0x79c80
	INCBIN "gfx/billboard/mon_silhouettes/caterpie.2bpp"
MetapodPic: ; 0x79e00
	INCBIN "gfx/billboard/mon_pics/metapod.2bpp"
MetapodSilhouettePic: ; 0x79f80
	INCBIN "gfx/billboard/mon_silhouettes/metapod.2bpp"
ButterfreePic: ; 0x7a100
	INCBIN "gfx/billboard/mon_pics/butterfree.2bpp"
ButterfreeSilhouettePic: ; 0x7a280
	INCBIN "gfx/billboard/mon_silhouettes/butterfree.2bpp"
WeedlePic: ; 0x7a400
	INCBIN "gfx/billboard/mon_pics/weedle.2bpp"
WeedleSilhouettePic: ; 0x7a580
	INCBIN "gfx/billboard/mon_silhouettes/weedle.2bpp"
KakunaPic: ; 0x7a700
	INCBIN "gfx/billboard/mon_pics/kakuna.2bpp"
KakunaSilhouettePic: ; 0x7a880
	INCBIN "gfx/billboard/mon_silhouettes/kakuna.2bpp"
BeedrillPic: ; 0x7aa00
	INCBIN "gfx/billboard/mon_pics/beedrill.2bpp"
BeedrillSilhouettePic: ; 0x7ab80
	INCBIN "gfx/billboard/mon_silhouettes/beedrill.2bpp"
PidgeyPic: ; 0x7ad00
	INCBIN "gfx/billboard/mon_pics/pidgey.2bpp"
PidgeySilhouettePic: ; 0x7ae80
	INCBIN "gfx/billboard/mon_silhouettes/pidgey.2bpp"

BonusMultiplierX1OnPic: ; 0x7b000
	INCBIN "gfx/billboard/slot/bonusmultiplierX1_on.2bpp"
BonusMultiplierX1OffPic: ; 0x7b180
	INCBIN "gfx/billboard/slot/bonusmultiplierX1_off.2bpp"
BonusMultiplierX2OnPic: ; 0x7b300
	INCBIN "gfx/billboard/slot/bonusmultiplierX2_on.2bpp"
BonusMultiplierX2OffPic: ; 0x7b480
	INCBIN "gfx/billboard/slot/bonusmultiplierX2_off.2bpp"
BonusMultiplierX3OnPic: ; 0x7b600
	INCBIN "gfx/billboard/slot/bonusmultiplierX3_on.2bpp"
BonusMultiplierX3OffPic: ; 0x7b780
	INCBIN "gfx/billboard/slot/bonusmultiplierX3_off.2bpp"
BonusMultiplierX4OnPic: ; 0x7b900
	INCBIN "gfx/billboard/slot/bonusmultiplierX4_on.2bpp"
BonusMultiplierX4OffPic: ; 0x7ba80
	INCBIN "gfx/billboard/slot/bonusmultiplierX4_off.2bpp"
BonusMultiplierX5OnPic: ; 0x7bc00
	INCBIN "gfx/billboard/slot/bonusmultiplierX5_on.2bpp"
BonusMultiplierX5OffPic: ; 0x7bd80
	INCBIN "gfx/billboard/slot/bonusmultiplierX5_off.2bpp"

INCBIN "baserom.gbc",$7bf00,$7c000 - $7bf00 ; 0x7bf00


SECTION "bank1f", ROMX, BANK[$1f]

SlowpokeAnimatedPic: ; 0x7c000
	INCBIN "gfx/billboard/mon_animated/slowpoke.2bpp"
MagnemiteAnimatedPic: ; 0x7c300
	INCBIN "gfx/billboard/mon_animated/magnemite.2bpp"
Farfetch_DAnimatedPic: ; 0x7c600
	INCBIN "gfx/billboard/mon_animated/farfetch_d.2bpp"
DoduoAnimatedPic: ; 0x7c900
	INCBIN "gfx/billboard/mon_animated/doduo.2bpp"
SeelAnimatedPic: ; 0x7cc00
	INCBIN "gfx/billboard/mon_animated/seel.2bpp"
GrimerAnimatedPic: ; 0x7cf00
	INCBIN "gfx/billboard/mon_animated/grimer.2bpp"
ShellderAnimatedPic: ; 0x7d200
	INCBIN "gfx/billboard/mon_animated/shellder.2bpp"
GastlyAnimatedPic: ; 0x7d500
	INCBIN "gfx/billboard/mon_animated/gastly.2bpp"
OnixAnimatedPic: ; 0x7d800
	INCBIN "gfx/billboard/mon_animated/onix.2bpp"
DrowzeeAnimatedPic: ; 0x7db00
	INCBIN "gfx/billboard/mon_animated/drowzee.2bpp"
KrabbyAnimatedPic: ; 0x7de00
	INCBIN "gfx/billboard/mon_animated/krabby.2bpp"
VoltorbAnimatedPic: ; 0x7e100
	INCBIN "gfx/billboard/mon_animated/voltorb.2bpp"
ExeggcuteAnimatedPic: ; 0x7e400
	INCBIN "gfx/billboard/mon_animated/exeggcute.2bpp"
CuboneAnimatedPic: ; 0x7e700
	INCBIN "gfx/billboard/mon_animated/cubone.2bpp"
HitmonleeAnimatedPic: ; 0x7ea00
	INCBIN "gfx/billboard/mon_animated/hitmonlee.2bpp"
HitmonchanAnimatedPic: ; 0x7ed00
	INCBIN "gfx/billboard/mon_animated/hitmonchan.2bpp"

INCBIN "baserom.gbc",$7f000,$80000 - $7f000 ; 0x7f000


SECTION "bank20", ROMX, BANK[$20]

LickitungAnimatedPic: ; 0x80000
	INCBIN "gfx/billboard/mon_animated/lickitung.2bpp"
KoffingAnimatedPic: ; 0x80300
	INCBIN "gfx/billboard/mon_animated/koffing.2bpp"
RhyhornAnimatedPic: ; 0x80600
	INCBIN "gfx/billboard/mon_animated/rhyhorn.2bpp"
ChanseyAnimatedPic: ; 0x80900
	INCBIN "gfx/billboard/mon_animated/chansey.2bpp"
TangelaAnimatedPic: ; 0x80c00
	INCBIN "gfx/billboard/mon_animated/tangela.2bpp"
KangaskhanAnimatedPic: ; 0x80f00
	INCBIN "gfx/billboard/mon_animated/kangaskhan.2bpp"
HorseaAnimatedPic: ; 0x81200
	INCBIN "gfx/billboard/mon_animated/horsea.2bpp"
GoldeenAnimatedPic: ; 0x81500
	INCBIN "gfx/billboard/mon_animated/goldeen.2bpp"
StaryuAnimatedPic: ; 0x81800
	INCBIN "gfx/billboard/mon_animated/staryu.2bpp"
Mr_MimeAnimatedPic: ; 0x81b00
	INCBIN "gfx/billboard/mon_animated/mr_mime.2bpp"
ScytherAnimatedPic: ; 0x81e00
	INCBIN "gfx/billboard/mon_animated/scyther.2bpp"
JynxAnimatedPic: ; 0x82100
	INCBIN "gfx/billboard/mon_animated/jynx.2bpp"
ElectabuzzAnimatedPic: ; 0x82400
	INCBIN "gfx/billboard/mon_animated/electabuzz.2bpp"
MagmarAnimatedPic: ; 0x82700
	INCBIN "gfx/billboard/mon_animated/magmar.2bpp"
PinsirAnimatedPic: ; 0x82a00
	INCBIN "gfx/billboard/mon_animated/pinsir.2bpp"
TaurosAnimatedPic: ; 0x82d00
	INCBIN "gfx/billboard/mon_animated/tauros.2bpp"

INCBIN "baserom.gbc",$83000,$84000 - $83000 ; 0x83000


SECTION "bank21", ROMX, BANK[$21]

MagikarpAnimatedPic: ; 0x84000
	INCBIN "gfx/billboard/mon_animated/magikarp.2bpp"
LaprasAnimatedPic: ; 0x84300
	INCBIN "gfx/billboard/mon_animated/lapras.2bpp"
DittoAnimatedPic: ; 0x84600
	INCBIN "gfx/billboard/mon_animated/ditto.2bpp"
EeveeAnimatedPic: ; 0x84900
	INCBIN "gfx/billboard/mon_animated/eevee.2bpp"
PorygonAnimatedPic: ; 0x84c00
	INCBIN "gfx/billboard/mon_animated/porygon.2bpp"
OmanyteAnimatedPic: ; 0x84f00
	INCBIN "gfx/billboard/mon_animated/omanyte.2bpp"
KabutoAnimatedPic: ; 0x85200
	INCBIN "gfx/billboard/mon_animated/kabuto.2bpp"
AerodactylAnimatedPic: ; 0x85500
	INCBIN "gfx/billboard/mon_animated/aerodactyl.2bpp"
SnorlaxAnimatedPic: ; 0x85800
	INCBIN "gfx/billboard/mon_animated/snorlax.2bpp"
ArticunoAnimatedPic: ; 0x85b00
	INCBIN "gfx/billboard/mon_animated/articuno.2bpp"
ZapdosAnimatedPic: ; 0x85e00
	INCBIN "gfx/billboard/mon_animated/zapdos.2bpp"
MoltresAnimatedPic: ; 0x86100
	INCBIN "gfx/billboard/mon_animated/moltres.2bpp"
DratiniAnimatedPic: ; 0x86400
	INCBIN "gfx/billboard/mon_animated/dratini.2bpp"
MewtwoAnimatedPic: ; 0x86700
	INCBIN "gfx/billboard/mon_animated/mewtwo.2bpp"
MewAnimatedPic: ; 0x86a00
	INCBIN "gfx/billboard/mon_animated/mew.2bpp"

INCBIN "baserom.gbc",$86d00,$88000 - $86d00 ; 0x86d00


SECTION "bank22", ROMX, BANK[$22]

ZubatAnimatedPic: ; 0x88000
	INCBIN "gfx/billboard/mon_animated/zubat.2bpp"
OddishAnimatedPic: ; 0x88300
	INCBIN "gfx/billboard/mon_animated/oddish.2bpp"
ParasAnimatedPic: ; 0x88600
	INCBIN "gfx/billboard/mon_animated/paras.2bpp"
VenonatAnimatedPic: ; 0x88900
	INCBIN "gfx/billboard/mon_animated/venonat.2bpp"
DiglettAnimatedPic: ; 0x88c00
	INCBIN "gfx/billboard/mon_animated/diglett.2bpp"
MeowthAnimatedPic: ; 0x88f00
	INCBIN "gfx/billboard/mon_animated/meowth.2bpp"
PsyduckAnimatedPic: ; 0x89200
	INCBIN "gfx/billboard/mon_animated/psyduck.2bpp"
MankeyAnimatedPic: ; 0x89500
	INCBIN "gfx/billboard/mon_animated/mankey.2bpp"
GrowlitheAnimatedPic: ; 0x89800
	INCBIN "gfx/billboard/mon_animated/growlithe.2bpp"
PoliwagAnimatedPic: ; 0x89b00
	INCBIN "gfx/billboard/mon_animated/poliwag.2bpp"
AbraAnimatedPic: ; 0x89e00
	INCBIN "gfx/billboard/mon_animated/abra.2bpp"
MachopAnimatedPic: ; 0x8a100
	INCBIN "gfx/billboard/mon_animated/machop.2bpp"
BellsproutAnimatedPic: ; 0x8a400
	INCBIN "gfx/billboard/mon_animated/bellsprout.2bpp"
TentacoolAnimatedPic: ; 0x8a700
	INCBIN "gfx/billboard/mon_animated/tentacool.2bpp"
GeodudeAnimatedPic: ; 0x8aa00
	INCBIN "gfx/billboard/mon_animated/geodude.2bpp"
PonytaAnimatedPic: ; 0x8ad00
	INCBIN "gfx/billboard/mon_animated/ponyta.2bpp"

INCBIN "baserom.gbc",$8b000,$8c000 - $8b000 ; 0x8b000


SECTION "bank23", ROMX, BANK[$23]

BulbasaurAnimatedPic: ; 0x8c000
	INCBIN "gfx/billboard/mon_animated/bulbasaur.2bpp"
CharmanderAnimatedPic: ; 0x8c300
	INCBIN "gfx/billboard/mon_animated/charmander.2bpp"
SquirtleAnimatedPic: ; 0x8c600
	INCBIN "gfx/billboard/mon_animated/squirtle.2bpp"
CaterpieAnimatedPic: ; 0x8c900
	INCBIN "gfx/billboard/mon_animated/caterpie.2bpp"
WeedleAnimatedPic: ; 0x8cc00
	INCBIN "gfx/billboard/mon_animated/weedle.2bpp"
PidgeyAnimatedPic: ; 0x8cf00
	INCBIN "gfx/billboard/mon_animated/pidgey.2bpp"
RattataAnimatedPic: ; 0x8d200
	INCBIN "gfx/billboard/mon_animated/rattata.2bpp"
SpearowAnimatedPic: ; 0x8d500
	INCBIN "gfx/billboard/mon_animated/spearow.2bpp"
EkansAnimatedPic: ; 0x8d800
	INCBIN "gfx/billboard/mon_animated/ekans.2bpp"
PikachuAnimatedPic: ; 0x8db00
	INCBIN "gfx/billboard/mon_animated/pikachu.2bpp"
SandshrewAnimatedPic: ; 0x8de00
	INCBIN "gfx/billboard/mon_animated/sandshrew.2bpp"
Nidoran_FAnimatedPic: ; 0x8e100
	INCBIN "gfx/billboard/mon_animated/nidoran_f.2bpp"
Nidoran_MAnimatedPic: ; 0x8e400
	INCBIN "gfx/billboard/mon_animated/nidoran_m.2bpp"
ClefairyAnimatedPic: ; 0x8e700
	INCBIN "gfx/billboard/mon_animated/clefairy.2bpp"
VulpixAnimatedPic: ; 0x8ea00
	INCBIN "gfx/billboard/mon_animated/vulpix.2bpp"
JigglypuffAnimatedPic: ; 0x8ed00
	INCBIN "gfx/billboard/mon_animated/jigglypuff.2bpp"

INCBIN "baserom.gbc",$8f000,$90000 - $8f000 ; 0x8f000


SECTION "bank24", ROMX, BANK[$24]

HypnoPic: ; 0x90000
	INCBIN "gfx/billboard/mon_pics/hypno.2bpp"
HypnoSilhouettePic: ; 0x90180
	INCBIN "gfx/billboard/mon_silhouettes/hypno.2bpp"
KrabbyPic: ; 0x90300
	INCBIN "gfx/billboard/mon_pics/krabby.2bpp"
KrabbySilhouettePic: ; 0x90480
	INCBIN "gfx/billboard/mon_silhouettes/krabby.2bpp"
KinglerPic: ; 0x90600
	INCBIN "gfx/billboard/mon_pics/kingler.2bpp"
KinglerSilhouettePic: ; 0x90780
	INCBIN "gfx/billboard/mon_silhouettes/kingler.2bpp"
VoltorbPic: ; 0x90900
	INCBIN "gfx/billboard/mon_pics/voltorb.2bpp"
VoltorbSilhouettePic: ; 0x90a80
	INCBIN "gfx/billboard/mon_silhouettes/voltorb.2bpp"
ElectrodePic: ; 0x90c00
	INCBIN "gfx/billboard/mon_pics/electrode.2bpp"
ElectrodeSilhouettePic: ; 0x90d80
	INCBIN "gfx/billboard/mon_silhouettes/electrode.2bpp"
ExeggcutePic: ; 0x90f00
	INCBIN "gfx/billboard/mon_pics/exeggcute.2bpp"
ExeggcuteSilhouettePic: ; 0x91080
	INCBIN "gfx/billboard/mon_silhouettes/exeggcute.2bpp"
ExeggutorPic: ; 0x91200
	INCBIN "gfx/billboard/mon_pics/exeggutor.2bpp"
ExeggutorSilhouettePic:  ; 0x91380
	INCBIN "gfx/billboard/mon_silhouettes/exeggutor.2bpp"
CubonePic: ; 0x91500
	INCBIN "gfx/billboard/mon_pics/cubone.2bpp"
CuboneSilhouettePic: ; 0x91680
	INCBIN "gfx/billboard/mon_silhouettes/cubone.2bpp"
MarowakPic: ; 0x91800
	INCBIN "gfx/billboard/mon_pics/marowak.2bpp"
MarowakSilhouettePic: ; 0x91980
	INCBIN "gfx/billboard/mon_silhouettes/marowak.2bpp"
HitmonleePic: ; 0x91b00
	INCBIN "gfx/billboard/mon_pics/hitmonlee.2bpp"
HitmonleeSilhouettePic: ; 0x91c80
	INCBIN "gfx/billboard/mon_silhouettes/hitmonlee.2bpp"
HitmonchanPic: ; 0x91e00
	INCBIN "gfx/billboard/mon_pics/hitmonchan.2bpp"
HitmonchanSilhouettePic: ; 0x91f80
	INCBIN "gfx/billboard/mon_silhouettes/hitmonchan.2bpp"
LickitungPic: ; 0x92100
	INCBIN "gfx/billboard/mon_pics/lickitung.2bpp"
LickitungSilhouettePic: ; 0x92280
	INCBIN "gfx/billboard/mon_silhouettes/lickitung.2bpp"
KoffingPic: ; 0x92400
	INCBIN "gfx/billboard/mon_pics/koffing.2bpp"
KoffingSilhouettePic: ; 0x92580
	INCBIN "gfx/billboard/mon_silhouettes/koffing.2bpp"
WeezingPic: ; 0x92700
	INCBIN "gfx/billboard/mon_pics/weezing.2bpp"
WeezingSilhouettePic: ; 0x92880
	INCBIN "gfx/billboard/mon_silhouettes/weezing.2bpp"
RhyhornPic: ; 0x92a00
	INCBIN "gfx/billboard/mon_pics/rhyhorn.2bpp"
RhyhornSilhouettePic: ; 0x92b80
	INCBIN "gfx/billboard/mon_silhouettes/rhyhorn.2bpp"
RhydonPic: ; 0x92d00
	INCBIN "gfx/billboard/mon_pics/rhydon.2bpp"
RhydonSilhouettePic: ; 0x92e80
	INCBIN "gfx/billboard/mon_silhouettes/rhydon.2bpp"

INCBIN "baserom.gbc",$93000,$94000 - $93000 ; 0x93000


SECTION "bank25", ROMX, BANK[$25]

MagnemitePic: ; 0x94000
	INCBIN "gfx/billboard/mon_pics/magnemite.2bpp"
MagnemiteSilhouettePic: ; 0x94180
	INCBIN "gfx/billboard/mon_silhouettes/magnemite.2bpp"
MagnetonPic: ; 0x94300
	INCBIN "gfx/billboard/mon_pics/magneton.2bpp"
MagnetonSilhouettePic: ; 0x94480
	INCBIN "gfx/billboard/mon_silhouettes/magneton.2bpp"
Farfetch_dPic: ; 0x94600
	INCBIN "gfx/billboard/mon_pics/farfetch_d.2bpp"
Farfetch_dSilhouettePic: ; 0x94780
	INCBIN "gfx/billboard/mon_silhouettes/farfetch_d.2bpp"
DoduoPic: ; 0x94900
	INCBIN "gfx/billboard/mon_pics/doduo.2bpp"
DoduoSilhouettePic: ; 0x94a80
	INCBIN "gfx/billboard/mon_silhouettes/doduo.2bpp"
DodrioPic: ; 0x94c00
	INCBIN "gfx/billboard/mon_pics/dodrio.2bpp"
DodrioSilhouettePic: ; 0x94d80
	INCBIN "gfx/billboard/mon_silhouettes/dodrio.2bpp"
SeelPic: ; 0x94f00
	INCBIN "gfx/billboard/mon_pics/seel.2bpp"
SeelSilhouettePic: ; 0x95080
	INCBIN "gfx/billboard/mon_silhouettes/seel.2bpp"
DewgongPic: ; 0x95200
	INCBIN "gfx/billboard/mon_pics/dewgong.2bpp"
DewgongSilhouettePic:  ; 0x95380
	INCBIN "gfx/billboard/mon_silhouettes/dewgong.2bpp"
GrimerPic: ; 0x95500
	INCBIN "gfx/billboard/mon_pics/grimer.2bpp"
GrimerSilhouettePic: ; 0x95680
	INCBIN "gfx/billboard/mon_silhouettes/grimer.2bpp"
MukPic: ; 0x95800
	INCBIN "gfx/billboard/mon_pics/muk.2bpp"
MukSilhouettePic: ; 0x95980
	INCBIN "gfx/billboard/mon_silhouettes/muk.2bpp"
ShellderPic: ; 0x95b00
	INCBIN "gfx/billboard/mon_pics/shellder.2bpp"
ShellderSilhouettePic: ; 0x95c80
	INCBIN "gfx/billboard/mon_silhouettes/shellder.2bpp"
CloysterPic: ; 0x95e00
	INCBIN "gfx/billboard/mon_pics/cloyster.2bpp"
CloysterSilhouettePic: ; 0x95f80
	INCBIN "gfx/billboard/mon_silhouettes/cloyster.2bpp"
GastlyPic: ; 0x96100
	INCBIN "gfx/billboard/mon_pics/gastly.2bpp"
GastlySilhouettePic: ; 0x96280
	INCBIN "gfx/billboard/mon_silhouettes/gastly.2bpp"
HaunterPic: ; 0x96400
	INCBIN "gfx/billboard/mon_pics/haunter.2bpp"
HaunterSilhouettePic: ; 0x96580
	INCBIN "gfx/billboard/mon_silhouettes/haunter.2bpp"
GengarPic: ; 0x96700
	INCBIN "gfx/billboard/mon_pics/gengar.2bpp"
GengarSilhouettePic: ; 0x96880
	INCBIN "gfx/billboard/mon_silhouettes/gengar.2bpp"
OnixPic: ; 0x96a00
	INCBIN "gfx/billboard/mon_pics/onix.2bpp"
OnixSilhouettePic: ; 0x96b80
	INCBIN "gfx/billboard/mon_silhouettes/onix.2bpp"
DrowzeePic: ; 0x96d00
	INCBIN "gfx/billboard/mon_pics/drowzee.2bpp"
DrowzeeSilhouettePic: ; 0x96e80
	INCBIN "gfx/billboard/mon_silhouettes/drowzee.2bpp"

INCBIN "baserom.gbc",$97000,$98000 - $97000 ; 0x97000


SECTION "bank26", ROMX, BANK[$26]

AlakazamPic: ; 0x98000
	INCBIN "gfx/billboard/mon_pics/alakazam.2bpp"
AlakazamSilhouettePic: ; 0x98180
	INCBIN "gfx/billboard/mon_silhouettes/alakazam.2bpp"
MachopPic: ; 0x98300
	INCBIN "gfx/billboard/mon_pics/machop.2bpp"
MachopSilhouettePic: ; 0x98480
	INCBIN "gfx/billboard/mon_silhouettes/machop.2bpp"
MachokePic: ; 0x98600
	INCBIN "gfx/billboard/mon_pics/machoke.2bpp"
MachokeSilhouettePic: ; 0x98780
	INCBIN "gfx/billboard/mon_silhouettes/machoke.2bpp"
MachampPic: ; 0x98900
	INCBIN "gfx/billboard/mon_pics/machamp.2bpp"
MachampSilhouettePic: ; 0x98a80
	INCBIN "gfx/billboard/mon_silhouettes/machamp.2bpp"
BellsproutPic: ; 0x98c00
	INCBIN "gfx/billboard/mon_pics/bellsprout.2bpp"
BellsproutSilhouettePic: ; 0x98d80
	INCBIN "gfx/billboard/mon_silhouettes/bellsprout.2bpp"
WeepinbellPic: ; 0x98f00
	INCBIN "gfx/billboard/mon_pics/weepinbell.2bpp"
WeepinbellSilhouettePic: ; 0x97080
	INCBIN "gfx/billboard/mon_silhouettes/weepinbell.2bpp"
VictreebellPic: ; 0x97200
	INCBIN "gfx/billboard/mon_pics/victreebell.2bpp"
VictreebellSilhouettePic:  ; 0x97380
	INCBIN "gfx/billboard/mon_silhouettes/victreebell.2bpp"
TentacoolPic: ; 0x97500
	INCBIN "gfx/billboard/mon_pics/tentacool.2bpp"
TentacoolSilhouettePic: ; 0x97680
	INCBIN "gfx/billboard/mon_silhouettes/tentacool.2bpp"
TentacruelPic: ; 0x97800
	INCBIN "gfx/billboard/mon_pics/tentacruel.2bpp"
TentacruelSilhouettePic: ; 0x97980
	INCBIN "gfx/billboard/mon_silhouettes/tentacruel.2bpp"
GeodudePic: ; 0x97b00
	INCBIN "gfx/billboard/mon_pics/geodude.2bpp"
GeodudeSilhouettePic: ; 0x97c80
	INCBIN "gfx/billboard/mon_silhouettes/geodude.2bpp"
GravelerPic: ; 0x97e00
	INCBIN "gfx/billboard/mon_pics/graveler.2bpp"
GravelerSilhouettePic: ; 0x97f80
	INCBIN "gfx/billboard/mon_silhouettes/graveler.2bpp"
GolemPic: ; 0x9a100
	INCBIN "gfx/billboard/mon_pics/golem.2bpp"
GolemSilhouettePic: ; 0x9a280
	INCBIN "gfx/billboard/mon_silhouettes/golem.2bpp"
PonytaPic: ; 0x9a400
	INCBIN "gfx/billboard/mon_pics/ponyta.2bpp"
PonytaSilhouettePic: ; 0x9a580
	INCBIN "gfx/billboard/mon_silhouettes/ponyta.2bpp"
RapidashPic: ; 0x9a700
	INCBIN "gfx/billboard/mon_pics/rapidash.2bpp"
RapidashSilhouettePic: ; 0x9a880
	INCBIN "gfx/billboard/mon_silhouettes/rapidash.2bpp"
SlowpokePic: ; 0x9aa00
	INCBIN "gfx/billboard/mon_pics/slowpoke.2bpp"
SlowpokeSilhouettePic: ; 0x9ab80
	INCBIN "gfx/billboard/mon_silhouettes/slowpoke.2bpp"
SlowbroPic: ; 0x9ad00
	INCBIN "gfx/billboard/mon_pics/slowbro.2bpp"
SlowbroSilhouettePic: ; 0x9ae80
	INCBIN "gfx/billboard/mon_silhouettes/slowbro.2bpp"

INCBIN "baserom.gbc",$9b000,$9c000 - $9b000 ; 0x9b000


SECTION "bank27", ROMX, BANK[$27]

INCBIN "baserom.gbc",$9c000,$a0000 - $9c000 ; 0x9c000


SECTION "bank28", ROMX, BANK[$28]

INCBIN "baserom.gbc",$a0000,$a4000 - $a0000 ; 0xa0000


SECTION "bank29", ROMX, BANK[$29]

INCBIN "baserom.gbc",$a4000,$a6000 - $a4000 ; 0xa4000

PalletTownPic: ; 0xa6000
	INCBIN "gfx/billboard/maps/pallettown.2bpp"
ViridianCityPic: ; 0xa6180
	INCBIN "gfx/billboard/maps/viridiancity.2bpp"
ViridianForestPic: ; 0xa6300
	INCBIN "gfx/billboard/maps/viridianforest.2bpp"
PewterCityPic: ; 0xa6480
	INCBIN "gfx/billboard/maps/pewtercity.2bpp"
MtMoonPic: ; 0xa6600
	INCBIN "gfx/billboard/maps/mtmoon.2bpp"
CeruleanCityPic: ; 0xa6780
	INCBIN "gfx/billboard/maps/ceruleancity.2bpp"
VermilionCitySeasidePic: ; 0xa6900
	INCBIN "gfx/billboard/maps/vermilioncityseaside.2bpp"
VermilionCityStreetsPic: ; 0xa6a80
	INCBIN "gfx/billboard/maps/vermilioncitystreets.2bpp"
RockMountainPic: ; 0xa6c00
	INCBIN "gfx/billboard/maps/rockmountain.2bpp"
LavenderTownPic: ; 0xa6d80
	INCBIN "gfx/billboard/maps/lavendertown.2bpp"
CeladonCityPic: ; 0xa6f00
	INCBIN "gfx/billboard/maps/celadoncity.2bpp"
CyclingRoadPic: ; 0xa7080
	INCBIN "gfx/billboard/maps/cyclingroad.2bpp"
FuchsiaCityPic: ; 0xa7200
	INCBIN "gfx/billboard/maps/fuchsiacity.2bpp"
SafariZonePic: ; 0xa7380
	INCBIN "gfx/billboard/maps/safarizone.2bpp"
SaffronCityPic: ; 0xa7500
	INCBIN "gfx/billboard/maps/saffroncity.2bpp"
SeafoamIslandsPic: ; 0xa7680
	INCBIN "gfx/billboard/maps/seafoamislands.2bpp"
CinnabarIslandPic: ; 0xa7800
	INCBIN "gfx/billboard/maps/cinnabarisland.2bpp"
IndigoPlateauPic: ; 0xa7980
	INCBIN "gfx/billboard/maps/indigoplateau.2bpp"

INCBIN "baserom.gbc",$a7b00,$a8000 - $a7b00 ; 0xa7b00

SECTION "bank2a", ROMX, BANK[$2a]

INCBIN "baserom.gbc",$a8000,$ac000 - $a8000 ; 0xa8000


SECTION "bank2b", ROMX, BANK[$2b]

INCBIN "baserom.gbc",$ac000,$b0000 - $ac000 ; 0xac000


SECTION "bank2c", ROMX, BANK[$2c]

INCBIN "baserom.gbc",$b0000,$b4000 - $b0000 ; 0xb0000


SECTION "bank2d", ROMX, BANK[$2d]

INCBIN "baserom.gbc",$b4000,$b8000 - $b4000 ; 0xb4000


SECTION "bank2e", ROMX, BANK[$2e]

INCBIN "baserom.gbc",$b8000,$bc000 - $b8000 ; 0xb8000


SECTION "bank2f", ROMX, BANK[$2f]

INCBIN "baserom.gbc",$bc000,$c0000 - $bc000 ; 0xbc000


SECTION "bank30", ROMX, BANK[$30]

INCBIN "baserom.gbc",$c0000,$c4000 - $c0000 ; 0xc0000


SECTION "bank31", ROMX, BANK[$31]

INCBIN "baserom.gbc",$c4000,$c8000 - $c4000 ; 0xc4000


SECTION "bank32", ROMX, BANK[$32]

INCBIN "baserom.gbc",$c8000,$cc000 - $c8000 ; 0xc8000


SECTION "bank33", ROMX, BANK[$33]

INCBIN "baserom.gbc",$cc000,$d0000 - $cc000 ; 0xcc000


SECTION "bank34", ROMX, BANK[$34]

INCBIN "baserom.gbc",$d0000,$d4000 - $d0000 ; 0xd0000


SECTION "bank35", ROMX, BANK[$35]

INCBIN "baserom.gbc",$d4000,$d8000 - $d4000 ; 0xd4000


SECTION "bank36", ROMX, BANK[$36]

INCBIN "baserom.gbc",$d8000,$dc000 - $d8000 ; 0xd8000


SECTION "bank37", ROMX, BANK[$37]

INCBIN "baserom.gbc",$dc000,$e0000 - $dc000 ; 0xdc000


SECTION "bank38", ROMX, BANK[$38]

INCBIN "baserom.gbc",$e0000,$e4000 - $e0000 ; 0xe0000


SECTION "bank39", ROMX, BANK[$39]

INCBIN "baserom.gbc",$e4000,$e8000 - $e4000 ; 0xe4000


SECTION "bank3a", ROMX, BANK[$3a]

INCBIN "baserom.gbc",$e8000,$ec000 - $e8000 ; 0xe8000


SECTION "bank3b", ROMX, BANK[$3b]

INCBIN "baserom.gbc",$ec000,$f0000 - $ec000 ; 0xec000


SECTION "bank3c", ROMX, BANK[$3c]

INCBIN "baserom.gbc",$f0000,$f4000 - $f0000 ; 0xf0000


SECTION "bank3d", ROMX, BANK[$3d]

INCBIN "baserom.gbc",$f4000,$f8000 - $f4000 ; 0xf4000


SECTION "bank3e", ROMX, BANK[$3e]

INCBIN "baserom.gbc",$f8000,$fc000 - $f8000 ; 0xf8000


SECTION "bank3f", ROMX, BANK[$3f]

INCBIN "baserom.gbc",$fc000,$fffff - $fc000 ; 0xfc000
